### ISSUE TITLE
Moved the sabre/* repos

### ISSUE THREAD

**Issue by evert** [sabre-io/dav#1007]
To: @DominikTo @untitaker @netgusto @jakobsack @staabm @Hywan @strokyl @BastiaanOlij @dennisdegreef @DeepDiver1975 @PVince81 @armin-hackmann @petrkotek @felixfbecker

Hey everyone!

I don't have a way to easily email you all, so I figured I'm just gonna open an issue and include all of you. I moved all the sabre/* repositories to its own organization. What this means is that it's much easier to control access to *all* repos, instead of me having to manually maintain lists of contributors.

So if you were part of the "To:" list above, it means you got an invite to be a member of this organization, and should have access to all repositories. Not interested? feel free to ignore this!

Anyway, as you might know from my previous blog posst, I no longer have a lot of time to work on sabre/* projects. Some day I might pick up some tasks again, but until then I want to help facilitate people to move forward with these projects.

Reference: https://evertpot.com/sabredav-maintenance-update/

You're in the list because I trust you and I've seen (bits) of your work and work ethic over multiple years. If you are now a member, feel free to:

* Do releases
* Close issues
* Merge PR's
* Invite other members

Let me know if you don't have access to something, or if you're unsure how to perform a certain task. I see my role today as a facilitator, but no longer a project runner. The future is yours!

**Comment by DeepDiver1975** [comment]
Thanks a lot for your trust @evert - I'm damn sure we will do our best to take care about sabre.

**Comment by DeepDiver1975** [comment]
I'll set up travis ....

**Comment by DeepDiver1975** [comment]
hmmm ... just lost admin rights ...

**Comment by DominikTo** [comment]
My fault. Fixed.

**Comment by untitaker** [comment]
Cool. I just subscribed to Baikal again, but I don't use it at all.

**Comment by DeepDiver1975** [comment]
> I'll set up travis ....

all integration still seem to be inplace - lets keep that for now and see how far we get ....

**Comment by felixfbecker** [comment]
I think it would make sense to rename the repos to drop the `sabre-` prefix then - i.e. the composer package `sabre/event` is under github.com/sabre/event, not github.com/sabre/sabre-event

**Comment by evert** [comment]
@felixfbecker I tried to get the `sabre` organization name several times over the past few years, but the owner didn't really want to let it go (hence sabre-io, it's the best we could come up with). I agree that it might make sense to drop the second sabre/* regardless though!

**Comment by untitaker** [comment]
>I think it would make sense to rename the repos to drop the sabre- prefix

There used to be a problem with email notifications being only tagged with `[dav]`, but since it's `[sabre/dav]` nowadays, :+1:

**Comment by DeepDiver1975** [comment]
Looks like travis is not triggered when pushing to this repo - see https://github.com/sabre-io/sabre-dav/pull/994

@evert can you please have a look where the issue might be - I have no access to the travis account. THX

**Comment by evert** [comment]
Taking a look @DeepDiver1975 , and making you an admin there if I can

**Comment by evert** [comment]
@DeepDiver1975 I think travis picked up the organization name change. I also manually restarted those builds. Let me know if there's still issues. Can you access this url now?

https://travis-ci.org/sabre-io/sabre-dav

**Comment by evert** [comment]
All repository names are now updated to their short names (dav instead of sabre-dav)

**Comment by DeepDiver1975** [comment]
Can you by chance grant rights to re-run travis jobs?

**Comment by evert** [comment]
Yea I'm just not sure how @DeepDiver1975 ! There doesn't seem real privilege management in travis, so I thought that you just _get_ the privilege by virtue of being a member of the sabre-io github org. Thoughts?

**Comment by DeepDiver1975** [comment]
Well ... looks like all just need to be a bit more patient ... sabre-io orga just popped up in travis. 👍

**Comment by staabm** [comment]
great move @evert. hopefully with this team we can maintain this great packages for the next years. <3

**Comment by DeepDiver1975** [comment]
Transition is done - I guess we can close this

**Comment by PVince81** [comment]
Any information about the release process ?
