### ISSUE TITLE
Path filter for any Sabre plugin

### ISSUE THREAD

**Issue by PVince81** [sabre-io/dav#1008]
Something like https://github.com/sabre-io/dav/blob/master/lib/DAV/PropertyStorage/Plugin.php#L38 but for any Sabre plugin.

Would allow for a more complex tree with path specific plugins.

ownCloud uses that a lot, currently the workaround is as follows: https://github.com/owncloud/core/blob/v10.0.3/apps/comments/lib/Dav/CommentsPlugin.php#L86

**Comment by DeepDiver1975** [comment]
The question is: how big is the overhead of calling initialize on every request? Did we analyze this?

**Comment by PVince81** [comment]
I think it's more about design pattern than overhead.

In general I think a plugin should not know to which endpoint it is attached and work only with node types/instances / resource types. The server decides on which endpoint to attach plugins, not the plugins themselves.

What do you think ?

**Comment by evert** [comment]
The problem with doing it during the `initialize` phase, is that there's quite a few types of HTTP requests that affect other parts of the tree.

For example, a CalDAV request might need stuff from the `principals/` tree. This is why these types of checks are not during `initialize` in the PropertyStorage plugin, but always in their respective events.

Another example of this is `COPY`. This HTTP method has both a source and a destination. Each can be in completely separate parts of the tree.

**Comment by PVince81** [comment]
Okay, you got some valid points. I'm closing this then.
