### ISSUE TITLE
Unsupported Media Type (Only allow valid card error) 

### ISSUE THREAD

**Issue by rehoehle** [sabre-io/dav#1010]
**Environment:** 

- Owncloud 10.0.3
- Contacts Plugin 1.5.3
- CalDav Synchroniser 2.25 or Thunderbird

**Explanation** 

Since some days we get a strange error in Owncloud. When you edit an existing contact or create a new one you get the following error and the contact isn't updated anymore. I can't reproduce the problem exactly but we got that problem with Linux with different Clients. 

```
{"reqId":"wx1ar0N8NZZhjiS8i8ri","level":4,"time":"2017-10-16T09:33:41+00:00","remoteAddr":"xxx","user":"xxx","app":"webdav","method":"PUT",
"url":"\/remote.php\/dav\/addressbooks\/users\/xxx\/contacts\/C7B8BB53-1DA0-0001-CE23-1080A5D01436.vlf","message":

"Exception: {\"Message\":\"HTTP\\\/1.1 415 This resource only supports valid vCard or jCard data. Parse error: This parser only supports VCARD and VCALENDAR files\",

\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\UnsupportedMediaType\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(316): 
Sabre\\\\CardDAV\\\\Plugin->validateVCard('BEGIN:VLIST\\\\r\\\\nPR...', false)\\n

#1 [internal function]: Sabre\\\\CardDAV\\\\Plugin->beforeCreateFile('addressbooks\\\/us...', 'BEGIN:VLIST\\\\r\\\\nPR...', Object(OCA\\\\DAV\\\\CardDAV\\\\AddressBook), false)\\n
#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1093): Sabre\\\\Event\\\\EventEmitter->emit('beforeCreateFil...', Array)\\n
#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('addressbooks\\\/us...', 'BEGIN:VLIST\\\\r\\\\nPR...', NULL)\\n
#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n
#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(234): Sabre\\\\DAV\\\\Server->exec()\\n
#10 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n
#11 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n
#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php\",\"Line\":356,\"User\":\"xxx\"}"}
```

The only possibility is to delete the contact in Outlook and create it again. If i can give some more informations i can do that.

**Comment by aluxnimm** [comment]
Outlook CalDav Synchronizer generetes VLIST vlf files to map Outlook distribution lists to the SOGo vlist format but that is obviously not supported in Owncloud/SabreDAV. So you have the wrong mapping options enabled and need to disable mapping of distribtion lists or use the vcard with kind:group option in the drop down in contact mapping configuration of the sync profile in Outlook.

**Comment by rehoehle** [comment]
I have the problem with Thunderbird and CalDav Sync. That are different products and if i delete the entry and generate the same again it's working again. I can't configure anything in that programs and it was working now for month. That problem appears randomly in the last days. We use the last versions for all programs.

**Comment by aluxnimm** [comment]
Thunderbird with SOGo connector? That also uses the SOGo VLIST format for contact groups which is not supported by Owncloud.

**Comment by DeepDiver1975** [comment]
Clearly not an issue of sabre dav - please open an issue in owncloud/core and mention me

> This parser only supports VCARD and VCALENDAR files

based on this information I'd say it is simply not supported and needs to be implemented ... one day.

I'm closing this in here
