### ISSUE TITLE
WebDav Client returns empty array for PROPFIND method

### ISSUE THREAD

**Issue by mehrdaad** [sabre-io/dav#1013]
I can assure that my webdav server is running and it's content is not empty by running:  
``` $ curl -X PROPFIND http://user:password@192.168.10.10/server/remote.php/webdav/Documents```  
But when I try to get list of files and dirs with Sabre WebDAV client it always returns empty array.  
Here's the equivalant code in client:  
```
<?php

use Sabre\DAV\Client;

include 'vendor/autoload.php';
$settings = array(
    'baseUri' => 'http://192.168.10.10/server/remote.php/webdav/',
    'userName' => 'user',
    'password' => 'password',
);
$client = new Client($settings);
try
{
    $response = $client->propFind('Documents', array(
        '{DAV:}displayname',
        '{DAV:}getcontentlength',
        print_r($directoryList);
} catch (Exception $e)
{
    print_r($e);
}
```
What am I doing wrong that returns empty array instead of directory contents?

**Comment by mehrdaad** [comment]
@DeepDiver1975 can you please answer it? I suspect this is a bug.

**Comment by Venhur** [comment]
You have to pass a third param with depth:
$client->propFind('Documents', array(
        '{DAV:}displayname',
        '{DAV:}getcontentlength'), 1)

**Comment by vaajnur** [comment]
very good! thank you!
