### ISSUE TITLE
Remove files that are older than 7 days?

### ISSUE THREAD

**Issue by SamihSoylu** [sabre-io/dav#1018]
Hi,

I have used this url to set up a client connection to my cloud storage.

http://sabre.io/dav/davclient/

My issue is that I would like to delete a folder within the remote url in the directory backups/databases/ if it is older than 7 days. 

How can I do this?

Thanks in advance!

**Comment by DeepDiver1975** [comment]
With a PROPFIND you can query for the last modified timestamp. With some basic arithmetic  you can detect folders/files which are older then 7 days.

about getlastmodified: https://tools.ietf.org/html/rfc4918#section-15.7
