### ISSUE TITLE
Can't get mailing feature from Microsoft Word to work

### ISSUE THREAD

**Issue by ArAcNiDe** [sabre-io/dav#1019]
Hi there!

I found a really weird problem using the mailing feature from Word.
When you try to load a list of receipients (from a .xlsx file for example), Word say that the file doesn't exist ... even when you can clearly see it in the file picker or in your explorer ...

Now you'll tell me : What does this have to do with Sabre?
Well, this only happen when you try to load your list from a WebDAV drive with Sabre-DAV-based implementation ; our own specific implementation behave the same way than Box.net's or owncloud's ones.
BUT ! If you create a WebDAV server using mod_dav (the Apache WebServer plugin), it will work perfectly fine!

I analysed the communications between Windows and both Sabre and mod_dav, and didn't find anything that would explain this behavior.
Did anyone experience something like this?

Thanks!

**Comment by DeepDiver1975** [comment]
Most probably because of Word requiring WebDAV locks which in ownCloud is only very limited implemented - no idea if box.net supports webDAV locks.

Anyway - this is not a Sabre issue but an issue in the implementation of the server.

Please get in touch with owncloud and/or box.net.

Thanks

**Comment by ArAcNiDe** [comment]
Box.net and owncloud was just 2 examples of other implementations with the same problem.
In our company (NetExplorer), we have our own implementation and the locking mecanism is fully supported and working fine.
I can't find anything that whould explain why our implementation is acting differently than mod_dav's one, and seeing that alternative implementations behave the same way makes me think that Sabre might be the cause.
It could be a missing property or header, or some piece of information Word doesn't have or doesn't understand that could explain this behavior.

I understand this might be one of Microsoft's magic bug, but I hoped someone have already had this problem and tried to find a workaround or a fix.

**Comment by DeepDiver1975** [comment]
> It could be a missing property or header, or some piece of information Word doesn't have or doesn't understand that could explain this behavior.

this is something you could then reverse engineer. In case you find anything please let us know. I have no knowledge about Word and DAV.
