### ISSUE TITLE
CalDAV Plugin gives an error

### ISSUE THREAD

**Issue by quicktrick** [sabre-io/dav#1024]
Hello!  I'm a newbie here, so please don't blame me much.

I use PHP 7.2, MySQL and Nginx.  I've cloned master branch from here and then executed `composer install`.  I imported all the mysql's sqls from the `examples` and I use my `server.php` taken from the examples too.  Everything seems working except `CalDAV Plugin`.  Now I have the following plugins working, as shown in the browser:

    core	The Core plugin provides a lot of the basic functionality required by WebDAV, such as a default implementation for all HTTP and WebDAV methods.	
    auth	Generic authentication plugin	
    browser	Generates HTML indexes and debug information for your sabre/dav server	
    sharing	This plugin implements WebDAV resource sharing	
    sync	Adds support for WebDAV Collection Sync (rfc6578)	
    acl	Adds support for WebDAV ACL (rfc3744)	
    subscriptions	This plugin allows users to store iCalendar subscriptions in their calendar-home.	
    caldav-schedule	Adds calendar-auto-schedule, as defined in rfc6638	
    caldav-sharing	Adds support for caldav-sharing.	
    ics-export	Adds the ability to export CalDAV calendars as a single iCalendar file.	
    carddav	Adds support for CardDAV (rfc6352)	
    vcf-export	Adds the ability to export CardDAV addressbooks as a single vCard file.

I have the following code in my `server.php`:

    ...
    $baseUri = '/';
    
    $authBackend = new Sabre\DAV\Auth\Backend\PDO($pdo);
    $principalBackend = new Sabre\DAVACL\PrincipalBackend\PDO($pdo);
    $carddavBackend = new Sabre\CardDAV\Backend\PDO($pdo);
    $caldavBackend    = new Sabre\CalDAV\Backend\PDO($pdo);
    
    $nodes = [
        new Sabre\DAVACL\PrincipalCollection($principalBackend),
        new Sabre\CalDAV\CalendarRoot($principalBackend, $caldavBackend),
        new Sabre\CardDAV\AddressBookRoot($principalBackend, $carddavBackend),
    ];
    
    $server = new Sabre\DAV\Server($nodes);
    $server->setBaseUri($baseUri);
    
    //$server->addPlugin(new Sabre\CalDAV\Plugin());
    ...

Everything is working fine until I uncomment the line adding `CalDAV Plugin`.  After that I have the following error in my browser:

    <?xml version="1.0" encoding="utf-8"?>
    <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
      <s:sabredav-version>4.0.0-alpha1</s:sabredav-version>
      <s:exception>TypeError</s:exception>
      <s:message>trim() expects parameter 1 to be string, null given</s:message>
    </d:error>

I guess that the error appears in the file `lib/CalDAV/Plugin.php`, somewhere here:

    function getCalendarHomeForPrincipal($principalUrl) {
        $parts = explode('/', trim($principalUrl, '/'));
        if (count($parts) !== 2) return;
        if ($parts[0] !== 'principals') return;
        return self::CALENDAR_ROOT . '/' . $parts[1];
    }

But I don't know how to fix it. After all, I'm not a PHP programmer (though I have quite a lot of programming experience in C# on Windows).

Please, help me fix this error. Thanks in advance!

**Comment by staabm** [comment]
Hmmm why dont you use the latest stable version? It seems you are using a alpha of 4.x?

**Comment by evert** [comment]
Yea the master branch was a wip to add typehinting to every file. Would be nice to get it done one day, but it wasn't ready.

**Comment by quicktrick** [comment]
Everything is working fine with the stable version.  Thanks a lot!

**Comment by OgreTransporter** [comment]
To complete this ticket, here the complete error:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>4.0.0-alpha1</s:sabredav-version>
  <s:exception>TypeError</s:exception>
  <s:message>trim() expects parameter 1 to be string, null given</s:message>
  <s:file>D:\htdocs\cal\vendor\sabre\dav\lib\DAV\Tree.php</s:file>
  <s:line>57</s:line>
  <s:code>0</s:code>
  <s:stacktrace>#0 D:\htdocs\cal\vendor\sabre\dav\lib\DAV\Tree.php(57): trim(NULL, '/')
#1 D:\htdocs\cal\vendor\sabre\dav\lib\CalDAV\Plugin.php(80): Sabre\DAV\Tree-&gt;getNodeForPath(NULL)
#2 D:\htdocs\cal\vendor\sabre\dav\lib\DAV\Server.php(520): Sabre\CalDAV\Plugin-&gt;getHTTPMethods('')
#3 D:\htdocs\cal\vendor\sabre\dav\lib\DAV\CorePlugin.php(825): Sabre\DAV\Server-&gt;getAllowedMethods('')
#4 D:\htdocs\cal\vendor\sabre\dav\lib\DAV\Browser\PropFindAll.php(53): Sabre\DAV\CorePlugin-&gt;Sabre\DAV\{closure}()
#5 D:\htdocs\cal\vendor\sabre\dav\lib\DAV\CorePlugin.php(827): Sabre\DAV\Browser\PropFindAll-&gt;handle('{DAV:}supported...', Object(Closure))
#6 D:\htdocs\cal\vendor\sabre\event\lib\WildcardEmitterTrait.php(89): Sabre\DAV\CorePlugin-&gt;propFind(Object(Sabre\DAV\Browser\PropFindAll), Object(Sabre\DAV\SimpleCollection))
#7 D:\htdocs\cal\vendor\sabre\dav\lib\DAV\Server.php(1053): Sabre\DAV\Server-&gt;emit('propFind', Array)
#8 D:\htdocs\cal\vendor\sabre\dav\lib\DAV\Browser\Plugin.php(340): Sabre\DAV\Server-&gt;getPropertiesByNode(Object(Sabre\DAV\Browser\PropFindAll), Object(Sabre\DAV\SimpleCollection))
#9 D:\htdocs\cal\vendor\sabre\dav\lib\DAV\Browser\Plugin.php(143): Sabre\DAV\Browser\Plugin-&gt;generateDirectoryIndex('')
#10 D:\htdocs\cal\vendor\sabre\event\lib\WildcardEmitterTrait.php(89): Sabre\DAV\Browser\Plugin-&gt;httpGet(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#11 D:\htdocs\cal\vendor\sabre\dav\lib\DAV\Server.php(464): Sabre\DAV\Server-&gt;emit('method:GET', Array)
#12 D:\htdocs\cal\vendor\sabre\dav\lib\DAV\Server.php(241): Sabre\DAV\Server-&gt;invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#13 D:\htdocs\cal\calendarserver.php(76): Sabre\DAV\Server-&gt;start()
#14 {main}</s:stacktrace>
</d:error>
```
You can use the following workarround in Tree.php, line 57:
```if ($path == null) $path = '/';```

**Comment by m-a-v** [comment]
I get the same error after an upgrade from 3.2.2. I am installing sabre/dav with the following command.

composer require sabre/dav ~4.0.0

With the workaround from the last comment it works for me.
