### ISSUE TITLE
composer --no-dev

### ISSUE THREAD

**Issue by htmldiz** [sabre-io/dav#1040]
Hi. I have same problem with php version and composer.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sabre/http dev-master -> satisfiable by sabre/ht
p[dev-master].
    - sabre/http dev-master requires php >=7.0 -> your PHP version (5.6.19) doe
 not satisfy that requirement.
  Problem 2
    - sabre/xml 2.1.0 requires php >=7.0 -> your PHP version (5.6.19) does not
atisfy that requirement.
    - sabre/xml 2.0.0 requires php >=7.0 -> your PHP version (5.6.19) does not
atisfy that requirement.
    - Installation request for sabre/xml ^2.0.0 -> satisfiable by sabre/xml[2.0
0, 2.1.0].

Running update with --no-dev does not mean require-dev is ignored, it just mean
 the packages will not be installed. If dev requirements are blocking the updat
 you have to resolve those problems.

**Comment by staabm** [comment]
so what is this issue about? what is the problem we should solve?

**Comment by htmldiz** [comment]
I just as how i can fix ed without change php version.

**Comment by staabm** [comment]
what do you try to achieve?
why do you install dev-master versions of the component?

**Comment by htmldiz** [comment]
I just try install your library without examples end any test files.

**Comment by htmldiz** [comment]
Can you help me please.

**Comment by staabm** [comment]
see http://sabre.io/dav/

**Comment by htmldiz** [comment]
So you just ignore me. Thanks a lot.

**Comment by staabm** [comment]
as I still dont know what you are trying todo I cannot help you.

the installation procedure is described on http://sabre.io/dav/install/ in detail

**Comment by DeepDiver1975** [comment]
Please follow this link to see which version of sabre you need for which php version - http://sabre.io/dav/install/

**Comment by htmldiz** [comment]
@DeepDiver1975 Thanks its help!

**Comment by DeepDiver1975** [comment]
I guess we can close this
