### ISSUE TITLE
oulook dav cfos.de client compatibility

### ISSUE THREAD

**Issue by reylon** [sabre-io/dav#1041]
Hi, I used in the past outlook dav cfos.de with owncloud. I cannot find now the correct configuration link to use with nextcloud 13. Using the default nextcloud link by the addressbook page, outlook dav not give error but not sync nothing. Is there a people that already configured it successfully? Thanks

**Comment by aluxnimm** [comment]
Try Outlook Caldav Synchronizer, we have a dedicated Nextcloud profile type and it's Open Source.

https://github.com/aluxnimm/outlookcaldavsynchronizer

**Comment by DeepDiver1975** [comment]
@reylon please get in touch with owncloud or nextcloud developers on their forums. THX
