### ISSUE TITLE
tag a new releaese

### ISSUE THREAD

**Issue by staabm** [sabre-io/dav#1050]
we should tag a new release with up2date dependencies for all the sabre/* dependencies

**Comment by staabm** [comment]
@DeepDiver1975 maybe I ask you to get a release out for sabre/dav ?

**Comment by DeepDiver1975** [comment]
release on 3.3 or 3.2 or both? ;-)

we shall discuss what from master is worth merging into either of these branches

**Comment by staabm** [comment]
I feel the most usefull way would be to create a new feature release branch (so 3.3), merging all non-breaking master-only changes into it, update the dependencies and release 3.3.

If time allows we could also create another 3.2.* just with updated vendors.

**Comment by DeepDiver1975** [comment]
we already have a branch 3.3 - it's diff to master looks like this: https://github.com/sabre-io/dav/compare/3.3...master

**Comment by DeepDiver1975** [comment]
I'll open a PR tonight to merge back changes from master to 3.3 branchs - include updating changelog and so one

do we want to wait for the changes as proposed by @icewind1991 in his to latest PRs ?

**Comment by staabm** [comment]
> we already have a branch 3.3 - it's diff to master looks like this: 3.3...master


ohh you are right. didn't realized we have a 3.3 branch already, since no 3.3.* release is available yet.



> I'll open a PR tonight to merge back changes from master to 3.3 branchs - include updating changelog and so one

that would be awesome! thx.

> do we want to wait for the changes as proposed by @icewind1991 in his to latest PRs ?

only in case you, or @evert is able to review and approve it in time. in case this is not possible, we should release without the PR.

**Comment by gharlan** [comment]
https://github.com/sabre-io/dav/blob/master/composer.json#L21
sabre/http 5.0 should be released, too.

**Comment by DeepDiver1975** [comment]
will do a sabre release session tonight ....

**Comment by evert** [comment]
Yea please kill the 3.2 branch =) 3.3 was ready a long time ago imho and it's pretty much compatible with 3.2.

**Comment by staabm** [comment]
@DeepDiver1975 do you have time to create a new alpha6.. ? maybe we could also declare it stable since we had a lot of alphas already (or maybe do a beta?)

**Comment by DeepDiver1975** [comment]
Sure .... will submit a PR asap. I'm find building a beta.
