### ISSUE TITLE
The main difference between sharedCalendar and subcription calendar

### ISSUE THREAD

**Issue by tuanlc** [sabre-io/dav#1053]
Hello,

I'm working on the task to implement sharing a resource for the address book in our [plugin](https://github.com/linagora/esn-sabre) and I'm referring to the implementation of the calendar.

I saw that shared calendar and subscription calendar are the results of subscribing action on a resource. So why we need two concepts in this case? What is the main point here, please?

**Comment by DeepDiver1975** [comment]
From my understanding subscriptions a read only

**Comment by tuanlc** [comment]
Is there a case that owner set public right to read/write? If yes, then the subscription is not read-only, right?

**Comment by evert** [comment]
Subscriptions are a server-stored list of .ics feed urls. It only contains the urls to other external feeds. This list of feeds can be consumed by at least iCal on OS X.

The subscription list doesn't contain any actual events. It's really just the urls. Like a list of 'bookmarks'.

Shared calendars are full server-managed calendars that look and behave like CalDAV calendars, except they may be read-only and owned by someone else.

**Comment by staabm** [comment]
I guess we should add this great piece of information of Everts comments into the class comments...

**Comment by heroandtn3** [comment]
@evert If I understand well, shared calendar works like this:

- A shares calendar X to B with write access
- B creates an event in the shared calendar X (because he has write access)
- The event is then created in X, both A and B can see the event

The same thing happens when B subscribes on calendar X with write access, hence, they seems to be the same. Can you tell me what I am missing?

**Comment by evert** [comment]
@heroandtn3 I guess if you take the end-users perspective, you might think that they more or less can accomplish the same use-case for read-only calendars. The implementation is drastically different though.

**Comment by heroandtn3** [comment]
@evert thanks for your answer, I understand them better now.

**Comment by tuanlc** [comment]
Thank you so much @evert for your detail explanation.
