### ISSUE TITLE
Split the WebDAV client out into seperate project

### ISSUE THREAD

**Issue by lightswitch05** [sabre-io/dav#1057]
This is a feature request. I've found the [WebDAV client](https://github.com/sabre-io/dav/blob/master/lib/DAV/Client.php). As far as I can tell, this is the only PHP WebDAV client in existence today. It would be useful if this client was moved it its own repo so that it could be used as a composer package. 

Thank you for providing this great project 👍

**Comment by lightswitch05** [comment]
well I'm an idiot https://github.com/sabre-io/davclient

**Comment by evert** [comment]
Unfortunately that separate project was never really completed. But yea, the goal was to make that separate repo better and then remove the client from this project.
