### ISSUE TITLE
Strange file conversion happens with vCard files

### ISSUE THREAD

**Issue by Offerel** [sabre-io/dav#1061]
I use SabreDAV release 3.22 to store my private files. Server is Nginx 1.13 on Debian 9. If i upload a file called contacts.vcf with multiple contacts as a file to the WebDAV share, the file is uploaded correctly. But when i download or view the file in a browser, some strange conversion happen. The file contacts.vcf have multiple contacts inside (it's a backup from the Android contacts app). If i open them on the servers console, the file is intact and i see all my contacts. Every contact begins with 
```
BEGIN:VCARD
VERSION:2.1
...
```
But when i view the file via a client like a browser or WebDAV client or i copy this file from server to a client device, i have afterwards only 1 contact inside. Additionally the file starts now with 
```
BEGIN:VCARD
VERSION:3.0
...
```
BTW: If i rename the file on the server to contacts.vcf.txt, transfer it and rename it back to contacts.vcf, the file stays intact.

Why does this happen? What could i do? Does anyone have a idea?

**Comment by evert** [comment]
In CardDAV vcards may only hold 1 contact. The server will strip off any additional contacts.

**Comment by Offerel** [comment]
Hi evert. Nice to see you here. 

I think it's a misunderstanding. I have created a kind of groupware file. This PHP file integrates CardDAV, CalDAV, as well as WebDAV in a single file. For this issue, I only use WebDAV. I copy the export of the Android Google Contacts App as a file to the WebDAV server. This export contains all contacts. In this test case a total of 8 contacts. The file arrives correctly on the server. I can display them with "cat contacts.vcf". The content appears as expected. If I copy this file back to Android or click on it via the browser plugin in the browser, only the first contact is transferred and the vCard version is changed from 2.1 to 3.0. But I would have expected the file to be displayed unchanged in the editor.

For a test I have set `//$server->addPlugin(new \Sabre\CardDAV\Plugin());` . In this case, the file is displayed correctly in a simple text editor. I think, I could only use separate files for CalDAV/CardDAV and another one for WebDAV as workaround. But I'd like to avoid that, though.

**Comment by evert** [comment]
I just had a look at the source, and you're completely right. We don't just convert vCards in the 'carddav tree', but also anywhere else there's a file with `text/vcard`. That's a little unexpected, and I can see that that could result in data loss. It's definitely a bit risky.

The plugin basically ensures that any vcard gets converted to version 3.0 (or 4.0 if requested).

**Comment by Offerel** [comment]
Many thx for investigation. If I understand this correctly, I can use my previous groupware file with the commented `//$server->addPlugin(new \Sabre\CardDAV\Plugin());` without problems. Both DAVDroid and eM Client seem to handle this without any problems and continue to synchronize newly created contacts without any problems. Only Roundcube does not work as expected and get a Status 415. If there is a fix, I can remove the comment characters again. Unfortunately, I'm not that deep in the code that I dare to fix it myself.

**Comment by evert** [comment]
Glad that worked for you. I definitely think this is an issue and _should_ be fixed correctly, but I'm not entirely sure yet what the right approach for this one is.

**Comment by Offerel** [comment]
I have new infos for you. If I disable GuessContentType Plugin with `//$server->addPlugin(new \Sabre\DAV\Browser\GuessContentType());` it works also as expected and the file isn't converted. So maybe his helps to identify a solution.
