### ISSUE TITLE
Asking for permission to use sabre/dav name and logo in Thunderbird AddOn

### ISSUE THREAD

**Issue by jobisoft** [sabre-io/dav#1067]
I am the developer of TbSync, a sync Addon for Thunderbird. It started as a pure sync solution for Exchange ActiveSync but is currently opening up by supporting external/additional sync providers, like Exchange WebServices and CalDAV/CardDAV.

For the CalDAV/CardDAV prototype I want to explicitly connect it to sabre/dav, because I want to use the discovery mechanism. So the provider will be called "sabre/dav (CalDAV/CardDAV) provider for TbSync". I also want to use the sabre/dav logo.

It will look like this

![image](https://github.com/jobisoft/EWS-4-TbSync/raw/master/screenshots/add_account.png)
More Information and the current prototype can be found here:
https://github.com/jobisoft/DAV-4-TbSync

**Am I allowed to use the name and the logo in this context?**

**Comment by DeepDiver1975** [comment]
I could not imagine and reason why not - but I'll leave this to others to finally answer @evert @staabm anybody else?

**Comment by staabm** [comment]
its everts call. I dont know who owns the name and/or logos.

**Comment by jobisoft** [comment]
Follow up question:

If someone knows, what license has the logo? TbSync will be shipped with Debian and I had to make sure all icons used are free incl. redistribution and modifications.

If the DAV provider will ever get anywhere and will also be shipped with Debian, I would need to know the actual licence, to know if this will work or not (a very theoretical question at the moment).

**Comment by evert** [comment]
Hi! Technically the name and logo is owned by fruux (which I am a partial owner of).

Totally cool with this! A bunch of other tools have the name & logo integrated, but you're the first to ask I think ;)

As an aside, the discovery mechanism is actually not sabre/dav specific and should work for other Cal/CardDAV servers as well.

Good luck with your project!

**Comment by jobisoft** [comment]
Nice, thanks for the feedback!

**Comment by jobisoft** [comment]
This is a small follow up questions: I only have access to owncloud servers (which uses sabre/dav) but not a plain sabre/dav server. The difference is, sabre/dav uses digest auth. Is there a chance to get a limited test account on a plain sabre/dav (test-) server, so i can test my digest auth implementation?

You can also contact me via email: john.bieling@gmx.de

Thanks,
John

**Comment by DeepDiver1975** [comment]
you can start this example: https://github.com/sabre-io/dav/blob/master/examples/groupwareserver.php

It uses an sqlite database which you need to setup first by applying the scripts from this folder https://github.com/sabre-io/dav/tree/master/examples/sql

**Comment by jobisoft** [comment]
Ok, I did set up my own server as you suggested, I added the rewrite rule to direct everything at groupwareserver.php and I can login with admin/admin by just going to https://dav.mydomain.tld

However the well-know discovery is not working. I get:

```
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>3.2.2</s:sabredav-version>
<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
<s:message>File not found: .well-known in 'root'</s:message>
</d:error>
```
Is it not part of groupwareserver.php?

**Comment by DeepDiver1975** [comment]
Wellknown is Something you usually Setup via Apache rewrite rules.

**Comment by jobisoft** [comment]
I did as described in the documentation (http://sabre.io/dav/service-discovery/) and it kinda works, because I do get an XML response from the server... but not the information I was requesting.

I do not want to missuse this issue as help ticket. I hoped someone could provide me with some test credentials to a working/existing test-server who is using digest auth, so I do not have to set up my own - and fail :-)

**Comment by jobisoft** [comment]
The problem was sitting in front of the computer ... restarting apache does help if the config has been changed ...

It is working now, thanks for your help!

**Comment by jobisoft** [comment]
So, digest auth is implemented. It works on my test system.

If anyone of you wants to try it out, and provide feedback, that would be awesome.

You need:
 - Thunderbird 52.*
 - TbSync-Beta: https://github.com/jobisoft/TbSync/releases/download/v0.7.10/TbSync-beta.xpi
 - DAV-4-TbSync v0.3: https://github.com/jobisoft/DAV-4-TbSync/releases/download/v0.3/DAV-4-TbSync.xpi

After adding a sabre/dav account and connecting, you should see a list of all your address books and calendars. CardDAV sync is missing. Calendars will simply be added to lightning. Since lightning does not yet support digest auth, that will fail. But you should get the list.
