### ISSUE TITLE
Introducing DAV-4-TbSync (Thunderbird)

### ISSUE THREAD

**Issue by jobisoft** [sabre-io/dav#1072]
Thanks to your awesome how-to guide I could finish my CalDAV/CardDAV synchronization AddOn for Thunderbird much faster than expected. 

It is designed as an additional provider for TbSync, currently published as an Exchange ActiveSync only AddOn, but the "wording" will change soon and it will become a general synchronization manager for Thunderbird with different providers available.

Long story short: You need [TbSync 0.7.10.20](https://github.com/jobisoft/TbSync/releases/download/v0.7.10/TbSync-beta.xpi) or later. When you try to add an CalDAV/CardDAV account, the required provider will be downloaded.

If someone wants to try this and provide feedback, that would be nice. Further information can be found on the [project page](https://github.com/jobisoft/DAV-4-TbSync) of the CalDAV/CardDAV provider for TbSync.

Thanks for all the quick help I received from this community.

**Comment by jobisoft** [comment]
I need your help once more :-(

The sync is working with my sabre/dav installation, different ownCloud installations, but not with your fruux.com. The discovery is not working.

```
** Sat Aug 18 2018 11:21:12 GMT+0200 **
[URL] : https://dav.fruux.com/.well-known/caldav/

** Sat Aug 18 2018 11:21:12 GMT+0200 **
[REQ] : <d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

** Sat Aug 18 2018 11:21:12 GMT+0200 **
[RESPONSE] : 404 : <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>3.1.0-alpha2</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File not found: .well-known in 'root'</s:message>
</d:error>
```
What am I doing wrong? Why do I get back well-known not found? I set up a new device in the fruux web-interface and I am using the generated user and password.

**Comment by jobisoft** [comment]
did you change something? now it works ... strange ...

**Comment by jobisoft** [comment]
It was the trailing slash, using "https://dav.fruux.com/.well-known/caldav" works as expected.

Other question: Is there a list of all possible HTTP status codes dav.fruux.com may return? And how to handle them? I get a 415 in combination with a "Sabre\DAV\Exception\ReportNotSupported", after trying to get the changes of a fresh/empty address book which still has a synctoken of "0".

What other codes may be returned?

**Comment by DeepDiver1975** [comment]
The http-Status Codes as defined by the rfcs. Fruux shall Not behave different

**Comment by jobisoft** [comment]
If the server throws a specific error code, there is usually an associated strategy to resolve the error by the client.

In the above example, where I get the 415 on a valid request, what should I do? Just ignore? 

Up to now I was working with Microsoft Exchange ActiveSync and they have a clear list, of what errors can be thrown and how to handle them. Is there anything like that for sabre/dav servers?

**Comment by jobisoft** [comment]
The Thunderbird team has just accepted and released the first version of TbSync, that officially supports my DAV provider:

https://addons.thunderbird.net/en-US/thunderbird/addon/tbsync/

*yeah*

**Comment by evert** [comment]
The `415` response definitely _sounds_ like a bug. I don't think there's a specific strategy to resolve it. When getting an error like that, it usually means that the client is using an incorrect format. If this is not the case, the server is probably broken?

**Comment by jobisoft** [comment]
I opened a new issue for this here:
https://github.com/sabre-io/dav/issues/1075

The Server is fruux and I *think* I follow the rules. :-(
