### ISSUE TITLE
How to install this on Laravel 5.6

### ISSUE THREAD

**Issue by skeeith** [sabre-io/dav#1078]
Could anyone tell me how to properly implement sabre/dav on Laravel 5.6?

It would be very helpful if anyone could share their setup with me.

**Comment by schel4ok** [comment]
What do you mean? 
Why do you need contacts and calendars on web site?
The only reason I can imagine is to create CRM.
But I think it is too complicated to create CRM from the scratch.
So what is your reason?

**Comment by asbiin** [comment]
I have implemented a connector here https://github.com/monicahq/laravel-sabre and I will be glad to have some feedback!

**Comment by evert** [comment]
Closing this. It's very hard to answer this without more context. All of these tools can be installed together with composer i assume.
