### ISSUE TITLE
iOS12 Authorization not working

### ISSUE THREAD

**Issue by dakhnod** [sabre-io/dav#1081]
With iOS < 12, my iPad was first sending every request without any Authorization header to my sabre CalDAV interface, to then repeat the same request with an Authorization Header included.
Since the last update to iOS12, it simply omits the second attempt with an Authorization header, thus sending no Authorization at all.

Did the type of Authorization on iOS change?
Is there anything i could do to adapt my code to iOS, or is this simply a problem with iOS?

**Comment by DeepDiver1975** [comment]
We at @owncloud are experiancing the same issue. Still researching about the reason ....

**Comment by DeepDiver1975** [comment]
Current research on this topic:
auth will only be sent if you have https AND a properly signed certificate - letscrypt seems to work

**Comment by rico** [comment]
@DeepDiver1975 this is an essential information and should make its way to the docs imho.

I tried to use a cert created with [mkcert](https://github.com/FiloSottile/mkcert) for local development. Unfortunately this does not work as well.
