### ISSUE TITLE
Anyone For Hire?

### ISSUE THREAD

**Issue by kornysnaps** [sabre-io/dav#1085]
We have basic contact and calendar data on another server in a database that is not in dav format.  The idea is to allow this data to be shared in caldav and carddav format.   Does anyone think they can take this task on?

**Comment by DeepDiver1975** [comment]
:wave:

**Comment by kornysnaps** [comment]
does that mean you are interested, DeepDiver?

**Comment by kornysnaps** [comment]
Hi Thomas,

How can we connect to discuss my Dav project?  I can be reached on skype with the username kornysnaps

Are you available?

Michael

**Comment by DeepDiver1975** [comment]
> does that mean you are interested, DeepDiver?

Please find my email in my public profile.
