### ISSUE TITLE
Share calendar

### ISSUE THREAD

**Issue by thovt93** [sabre-io/dav#1086]
Can I share calendar  and allow another people can full access to my calendar shared. It's mean another people can CURD my calendar objects.

**Comment by DeepDiver1975** [comment]
yes - owncloud has that implemented: https://github.com/owncloud/core/tree/master/apps/dav/lib

Going into details is a bit too much for a message in here.

Take this also as starting point: http://sabre.io/dav/caldav-sharing/

Happy debugging ;-)
