### ISSUE TITLE
release 3.2.3 & 3.1.5

### ISSUE THREAD

**Issue by staabm** [sabre-io/dav#1097]
while reviewing the changelog for 4.0.0-alpha4 I realized that we have implemented fixes for 3.2.* and 3.1.* without a release.

we should make a release for those versions

**Comment by staabm** [comment]
@DeepDiver1975 would you be interessted in creating those releases?

**Comment by DeepDiver1975** [comment]
the branches themselves are ready? Or are any changes missing which should go in here?

**Comment by DeepDiver1975** [comment]
What to do with 3.3?

Proposal
- delete branch
- move changelog of 3.3.0 into 4.0.0

objections?

@evert @staabm

**Comment by staabm** [comment]
IMO deleting the 3.3 branch makes sense, since it never saw a stable release (and it wont).

I would not adjust the changelog.

**Comment by DeepDiver1975** [comment]
3.1.5 and 3.2.3 released
branch 3.3 deleted

close

**Comment by staabm** [comment]
Thank you @DeepDiver1975 , well done.

**Comment by DennisBB** [comment]
The version number was not update for 3.2.3 It still shows 3.2.2 in this file lib/DAV/Version.php
