### ISSUE TITLE
Caldav on Mac vs iPhone

### ISSUE THREAD

**Issue by kornysnaps** [sabre-io/dav#1101]
I am able to add a new account on a Mac with a url similar to https://dav.server.com/calendarserver.php/principals/admin/

However, that url nor any url similar to it work on the iphone.  Has anyone else encountered this and found a solution?

**Comment by DeepDiver1975** [comment]
As far as I can tell IOS 12 requires a secure connection including a valid certificate chain.

**Comment by kornysnaps** [comment]
We have the certificate installed.  CardDav works on this iphone but CalDav just won't verify.

**Comment by DeepDiver1975** [comment]
Self signed cert? Please test the cert and Server setup : https://www.ssllabs.com/ssltest/

**Comment by Webbeh** [comment]
I have a related issue I reckon, although using NextCloud 18 (which uses sabre as dav backend).

Server is SSL-only with valid Let's Encrypt SSL chain.

The synchronization used to work with previous iOS versions but absolutely refuses to work with the recent ones. The phone just barfs a "Cannot Connect Using SSL".

**Comment by DeepDiver1975** [comment]
> I have a related issue I reckon, although using NextCloud 18 (which uses sabre as dav backend).

Best is to get in touch with the Nextcloud guys https://help.nextcloud.com

**Comment by Webbeh** [comment]
I do not believe this is a NextCloud issue,  but rather a iOS 13+  <-> dav issue.
It started appearing to me after  the phone update, but was fine before that.
