### ISSUE TITLE
Wikipedia on sabre/dav and CalDAV

### ISSUE THREAD

**Issue by dilyanpalauzov** [sabre-io/dav#1104]
Update at https://en.m.wikipedia.org/wiki/Comparison_of_CalDAV_and_CardDAV_implementations -> Server implementations the features of sabre/dav.

**Comment by staabm** [comment]
@dilyanpalauzov feel free to update the feature set mention on this wikipedia page.

**Comment by dilyanpalauzov** [comment]
I do not know what to write there.  I just contact all servers and client developers to update the information.

**Comment by DeepDiver1975** [comment]
> I do not know what to write there. I just contact all servers and client developers to update the information.

I question if this is a good way to waste life time ..... people working on github are developers - we write code but no wiki articles.
