### ISSUE TITLE
Move travis to new integration

### ISSUE THREAD

**Issue by DeepDiver1975** [sabre-io/dav#1109]
In January 2019 travis will stop working if we don't switch over to the new integration see https://developer.github.com/changes/2018-04-25-github-services-deprecation/

If you agree I'll activate move over.

@evert @staabm

**Comment by DeepDiver1975** [comment]
> Sure +1, in case the new builds support already all features we need

we will see ..... if not we have to adapt - there is no way to stay on the old system anyway ....

**Comment by staabm** [comment]
In case this is related to 
https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories

This is only for travis-ci.com (commercial) not yet for travis-ci.org (open source projects)

**Comment by DeepDiver1975** [comment]
As far as I understood this: travis-ci.org is dealing with the old integration (terminated by Jan 2019). The new integration is to be setup with travis-ci.com

**Comment by DeepDiver1975** [comment]
Looks like we can/have to wait .... they will send us an email ... https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg

**Comment by DeepDiver1975** [comment]
We will get notified one day -> I'm closing this for now

**Comment by staabm** [comment]
I guess we will move to github actions someday :-)
