### ISSUE TITLE
Grant full access rights to specific user

### ISSUE THREAD

**Issue by theendcomplete** [sabre-io/dav#1115]
Hi!
I'm currently using sabre dav as a part of Nextcloud 14 for sharing contacts.
Surprisingly, nextcloud admin user does not have access to regular users' addressbooks.

Is there any possibility to create adminuser for currently installed sabredav?

Maybe, any chance to disable ACL checking?

The purpose for all of this is to create address books via CLI for automatisation and integration with another systems.
Thank you!

**Comment by DeepDiver1975** [comment]
> The purpose for all of this is to create address books via CLI for automatisation and integration with another systems.

If you want to implement a cli tool which reads all addressbooks this is somehting to be implemented in the scope of nextcloud. It would be rather easy to load the backend classes and iterate over the addressbooks.

If you are looking into a way to disable the acl plugin for some users look at this https://github.com/sabre-io/dav/blob/62cfe9d497652bf3a687f59776a792c8d1fceb86/lib/DAVACL/Plugin.php#L104
