### ISSUE TITLE
WebDAV get path of created file

### ISSUE THREAD

**Issue by dakhnod** [sabre-io/dav#1118]
Lets consider the following scenario:
My WebDAV endpoint is called through a WebDAV client, creating a new file and writing the PUT body into that new file (a regular upload).
All of that happens inside of the $server->exec() call.

Now, after said exec()-call, is there any way to get the absolute path of that freshly uploaded/created file without modifying the library?

**Comment by evert** [comment]
You can create a plugin that listens for the afterCreateFile event:

http://sabre.io/dav/2.x/writing-plugins/
