### ISSUE TITLE
LockDiscovery owner data type ...

### ISSUE THREAD

**Issue by DeepDiver1975** [sabre-io/dav#1124]
refs https://github.com/sabre-io/dav/blob/62cfe9d497652bf3a687f59776a792c8d1fceb86/lib/DAV/Xml/Property/LockDiscovery.php#L99

I'd like to get a better understanding of the references code segment.

Looks like owner can be xml and in case a string with < > is used no owner will be output.

Example owner string: `foo <foo@bar.net>`

see https://github.com/owncloud/core/issues/33822

If we expect valid xml we should properly document this and add some verification logic

@evert mind sharing some insights? THX

**Comment by evert** [comment]
Hi!

You are right, the value can hold a full XML element. The RFC also confirms this:

https://tools.ietf.org/html/rfc4918#section-14.17

I didn't bother with this at first, but added support later when I moved to the new XML system. Some clients will send strings, and other clients will send an email address wrapped in a `<d:href>` element.

The reason I recall this was needed, is that I think some clients will actually use the contents of `<d:lockdiscovery/>` to find out if the 'current' user is the lock owner. But aside from that, it's also basically required from the specifications.

The easiest fix for you is to simply escape `<>&`.

**Comment by DeepDiver1975** [comment]
I'm closing this since this has to be taken care by the code base which is using this ....
