### ISSUE TITLE
CalDAV default availability

### ISSUE THREAD

**Issue by ok38** [sabre-io/dav#1127]
Hello,

I am using Sabre DAV for a little while, firstly thank you.

I am looking for default availability for new calendar event and until now, nothing found. Is there a way to do ?

Thank you.

**Comment by MrTasken** [comment]
You have to generate vavailability info and propatch that to the relevant inbox. 

To do it on the server you update the propertystorage table with the information you need:

- path => uri to users inbox (calendars/princpal/inbox)
- name => {urn:ietf:params:xml:ns:caldav}calendar-availability
- valuetype => 1
- value => BEGIN:VCALENDAR ... your vavailability component

**Comment by DeepDiver1975** [comment]
THX @MrTasken 

Closing this issue because of missing feedback from OP
