### ISSUE TITLE
Huge amount of schedulingobjects (database cleanup)

### ISSUE THREAD

**Issue by m-a-v** [sabre-io/dav#1138]
Is it normal that schedulingobjects use a lot of database space? In my case, the table uses 85% of the total database size.

Is it possible that a faulty client generates a large number of entries?

Is there a safe way to cleanup the database?

I'm grateful for any advice. Thank you!

**Comment by MrTasken** [comment]
I think it's the clients job to delete the "inboxed" events when they have processed it. I.e. given the user feedback, like "Attendee X has accepted". Then when pressed "OK" the client should send a delete request to the server (calendar inbox).

Yes I think it's a faulty client. 

Yes I think it's pretty safe to just delete all the entries, the events should have been automatically added/merged to the relevant user calendar already.

**Comment by m-a-v** [comment]
Thank you. Can someone confirm this?

**Comment by evert** [comment]
Hi! I added this functionality.

The list of items in the inbox mainly serve as notifications. Calendar applications might use it to notify users of new invites, changes to invitations or deletions.

As a rule of thumb, I don't think there is a point in keeping items in this list that happened before today. Items in that list are not the actual events. The events themselves are in users' calendars, so by deleting items from the inbox you're not really removing historical data.

**Comment by m-a-v** [comment]
Thank you very much. I really appreciate you taking the time to answer my question.

I think it would make sense to implement a daily cron job which executes deleteSchedulingObject on the backend for old scheduling objects.

**Comment by m-a-v** [comment]
@evert How is the logic for recurring events in the inbox (e.g. a weekly event). Is there only one scheduling object (ics file) in the schedulingobjects table? If this would be true, comparing only the start and end date would not be enough. Are there any helper functions to determine whether an event has been expired?

Is the calendarchanges also a table which could be cleaned up somehow? After cleaning the schedulingobjects table this would be the largest table.

**Comment by evert** [comment]
It's been a while since I looked at this, but the database _should_ have a column with a unix timestamp that's the last occurrence of any recurring or non-recurring event. I'm not sure anymore what value it holds for events that never end.

**Comment by m-a-v** [comment]
Thanks for the hint! Yes the calendarobjects table holds a column with lastoccurence data which was retrieved by the getDenormalizedData function. An event that never ends holds the value `MAX_DATE = '2038-01-01';`. Like this old events can be detected an deleted easily.

For the record: scheduling objects for already deleted calendarobjects should also be deleted from the schedulingobjects table.
