### ISSUE TITLE
ErrorException Undefined offset: 1 in findByUri

### ISSUE THREAD

**Issue by muelli** [sabre-io/dav#1149]
```
< 
< <?xml version="1.0" encoding="utf-8"?>
< <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<   <s:sabredav-version>3.1.3</s:sabredav-version>
<   <s:exception>ErrorException</s:exception>
<   <s:message>Undefined offset: 1</s:message>
< </d:error>
```

vendor/sabre/dav/lib/DAVACL/PrincipalBackend/PDO.php should use something like `array_pad`:

```
    function findByUri($uri, $principalPrefix) {
        $value = null;
        $scheme = null;
        list($scheme, $value) = array_pad(explode(":", $uri, 2), 2, null);
        if ($value == null) return null;

```

This is probably a sabredav issue though, but I don't know where to report it to.

**Comment by staabm** [comment]
E.g. https://github.com/thephpleague/uri-parser

**Comment by evert** [comment]
yeah or sabre/uri. I don't care either way but I think we already use that dependency ;)

**Comment by staabm** [comment]
Ohh right.. didn‘t remember there is a sabre equivalent.

Sabre/uri it should be then

**Comment by MTindev** [comment]
Issue linked to #1137

**Comment by staabm** [comment]
PR welcome

**Comment by tchapi** [comment]
Here you go : https://github.com/sabre-io/dav/pull/1210

**Comment by staabm** [comment]
fixed with https://github.com/sabre-io/dav/pull/1210
