### ISSUE TITLE
OS X Calendar does not find principal

### ISSUE THREAD

**Issue by rico** [sabre-io/dav#1151]
I try to make my setup compatible with OS X Calendar. Now if I specify _server_ address and the _path_ on the server (using advanced config of the account setup), and set the value to `/principals/user@domain.test`, everything works fine.

But if I omit the path (in manual config of the account setup), I get the message **unable to verify account name or password**.

When I log the requests mad to my dav server `https://dav.domain.test`, I get the following sequence:

    HEAD: https://dav.domain.test  
    HEAD: https://dav.domain.test  
    PROPFIND: https://dav.domain.test/caldav/v2  
    PROPFIND: https://dav.domain.test/principals/users/user%40domain.test  
    PROPFIND: https://dav.domain.test/principals
    PROPFIND: https://dav.domain.test/dav/principals

The methods `getChild($name)` and `getPrincipalByPath` and `getPrincipalByPath($path)` with the values `users` and `principals/users`, which does not work, obviously.

So, I added a rewrite rule to my nginx config to redirect ` https://dav.domain.test/principals/users/user%40domain.test` to ` https://dav.domain.test/principals/user%40domain.test`. Unfortunately this doesn't work as well (same error message).

The only thing I _customized_ in my setup is the implementation of `Sabre\DAV\Auth\Backend\BackendInterface` which extends  `Sabre\DAV\Auth\Backend\AbstractBasic`. The implementation returns `[true, principals/user@domain.test]` upon successful login (check).

I also use [laravel-sabre](https://github.com/monicahq/laravel-sabre) to integrate this (awesome!) project in my Laravel application. But I don't think this is the root of the issue.

Any help very welcome - thanks!

**Comment by evert** [comment]
It's a bit hard to tell what might go wrong here, without also having an idea of the return status codes and response bodies.

I can tell you that rewriting is a really bad idea. Absolutely turn this of.

* Where does the /caldav/v2 path come from?
* Maybe this helps: http://sabre.io/dav/service-discovery/

**Comment by rico** [comment]
@evert thank you for the quick reply.

All the `PROPFIND` requests return `404` - which makes sense, because these urls do not exist. For example `PROPFIND https://dav.domain.test/principals/users/user%40domain.test`

Returns `404` with body:

    <?xml version="1.0" encoding="utf-8"?>
    <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
        <s:sabredav-version>3.2.2</s:sabredav-version>
        <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
        <s:message>Principal with name users not found</s:message>
        <s:file>/Users/rico/smartcode/projects/trindu/code/vendor/sabre/dav/lib/DAVACL/AbstractPrincipalCollection.php</s:file>
        <s:line>121</s:line>
        <s:code>0</s:code>
        <s:stacktrace>#0 /Users/rico/smartcode/projects/project/code/vendor/sabre/dav/lib/DAV/Tree.php(76): Sabre\DAVACL\AbstractPrincipalCollection-&gt;getChild('users')
        [...]

Except for request `PROPFIND https://dav.domain.test/principals ` which returns:

    <d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/">
    	<d:response>
    		<d:href>
    			/principals/
    		</d:href>
    		<d:propstat>
    			<d:prop>
    				<d:resourcetype>
    					<d:collection />
    				</d:resourcetype>
    			</d:prop>
    			<d:status>
    				HTTP/1.1 200 OK
    			</d:status>
    		</d:propstat>
    	</d:response>
    	<d:response>
    		<d:href>
    			/principals/trainer1@yb.ch
    		</d:href>
    		<d:propstat>
    			<d:prop>
    				<d:resourcetype />
    			</d:prop>
    			<d:status>
    				HTTP/1.1 200 OK
    			</d:status>
    		</d:propstat>
    		<d:propstat>
    			<d:prop>
    				<d:getlastmodified /><d:getcontentlength /><d:quota-used-bytes /><d:quota-available-bytes /><d:getetag /><d:getcontenttype />
    			</d:prop>
    			<d:status>
    				HTTP/1.1 404 Not Found
    			</d:status>
    		</d:propstat>
    	</d:response>
    	<d:response>
    		<d:href>
    			/principals/172
    		</d:href>
    		<d:propstat>
    			<d:prop>
    				<d:resourcetype />
    			</d:prop>
    			<d:status>
    				HTTP/1.1 200 OK
    			</d:status>
    		</d:propstat>
    		<d:propstat>
    			<d:prop>
    				<d:getlastmodified /><d:getcontentlength /><d:quota-used-bytes /><d:quota-available-bytes /><d:getetag /><d:getcontenttype />
    			</d:prop>
    			<d:status>
    				HTTP/1.1 404 Not Found
    			</d:status>
    		</d:propstat>
    	</d:response>
    	<d:response>
    		<d:href>
    			/principals/171
    		</d:href>
    		<d:propstat>
    			<d:prop>
    				<d:resourcetype />
    			</d:prop>
    			<d:status>
    				HTTP/1.1 200 OK
    			</d:status>
    		</d:propstat>
    		<d:propstat>
    			<d:prop>
    				<d:getlastmodified /><d:getcontentlength /><d:quota-used-bytes /><d:quota-available-bytes /><d:getetag /><d:getcontenttype />
    			</d:prop>
    			<d:status>
    				HTTP/1.1 404 Not Found
    			</d:status>
    		</d:propstat>
    	</d:response>
    </d:multistatus>

... which makes sense to me, because it is a handled URL.

The path / url ` /caldav/v2` ist requested by the client, as are all the other paths. I'went through my setup and the principal prefix is set to `principals`. So I guess the OS X Calendar app is requesting those URL's hoping to get the principal or the calendar in the response.

I already added the redirect suggested in the docs for the service discovery to my nginx conf and made sure that it is working properly:

        rewrite ^/\.well-known/caldav / permanent;

OK - I removed the principals rewrite :-)

**Comment by rico** [comment]
I have now implemented the classes to get a custom principals uri `principals/users` as explained [here](http://sabre.io/dav/principals/).

The principal is now returned properly (from `principals/users/user%40domain.test`). However, the problem with service discovery remains. 

The next request from OS X Calendar app goes to `/dav/principals` (which returns a `404`), and then the process stops.

If I provide the _path_ in the advanced config, everything works fine, but service discovery does not work.

**Comment by evert** [comment]
I think in general (if I recall this correctly, it's been a while) a OS/X calendar will first look for the current-user-principal property. As long as that works, I feel this should work.

But it sounds like you've made some bigger changes. The best recommendation I can give is to try and compare your results with the results from a working CalDAV server.

**Comment by rico** [comment]
@evert thanks for your reply.

>  OS/X calendar will first look for the current-user-principal property

And how / where does it look for that property?

> try and compare your results with the results from a working CalDAV server.

You mean in terms of requests made / responses received, using a proxy (e.g. Charles)? Is there any working demo instance for sabre/dav?

- thanks

**Comment by evert** [comment]
I don't have a live system running somewhere, but https://fruux.com/ uses an older version and should work fine.

I think OS X calendar will look for the current-user-principal property in whatever url it was redirected to, so if your well-known redirect points to `/`, it will look for it there.

**Comment by rico** [comment]
@evert - ok, thanks for the info.

I just searched the source code for `current-user-principal` and noticed, that is only used in the ACL Plugin. I do not have that in my setup , so that might be something to check as well.

**Comment by evert** [comment]
Ok there's your problem. The ACL plugin is absolutely required for Cal/CardDAV. Tons of stuff will break without it.

**Comment by rico** [comment]
@evert yep - that was ist :-) Just added `\Sabre\DAVACL\Plugin()` to my setup and service discovery works.

Thank you very much for your time!
