### ISSUE TITLE
Better ACL examples

### ISSUE THREAD

**Issue by tasso85** [sabre-io/dav#1154]
I have checked the docs about the ACL at http://sabre.io/dav/acl/ in which it is said that

> What ACL is not:
> This will not magically work in WebDAV clients. In fact, none of the standard WebDAV clients I've tested have support for this. So even though ACL is enforced on the server, clients might not properly display ACL information, let alone change it.
> This will not allow you to lock down your filesystem. ACL support purely exists as a developer API if you create your own node classes.

However I think it would be really useful to have a more complete example on how an ACL may be setup with SabreDAV server, so that it is enforced at least on server side, preventing a user to open/edit documents for which s/he has not the permission to do so.

**Comment by evert** [comment]
Hi @tasso85 ,

I don't disagree but.. have you read RFC3744? It's pretty much required reading.

**Comment by tasso85** [comment]
I must confess I only gave it a quick look, trying to understand how the RFC is implemented in the various classess of the package, but I wasn't really successful, and that's what prompted my suggestion.

I *think* I grasped some of it, but I do not really see how to "translate" it using the variouls ACL classes of this package, specifically for assigning permission to single users instead of say all authenticated ones.

**Comment by woutersamaey** [comment]
Also interested to see more examples and what can be done to make some dirs read-only for example.

**Comment by evert** [comment]
I think a big question anyone using the ACL system should ask is: Do you want full support for RFC3744.

It's a good foundation for doing ACL, but many people have much simpler requirements for ACL and it might just suffice to send the appropriate `Forbidden` exception when a user does something they shouldn't.

If you're implementing just a file store, I am not aware of any clients that actually take advantage of RFC3744 to understand what a user may and may not do.

That said, it's still a really good framework for doing complex ACL. It just comes with a level of complexity that most people probably don't need.

I would strongly suggest you read RFC3744 first though, and come back with specific questions once you have. I am probably not going to be one writing more documentation for this, but the website is open source and contributions are appreciated. Especially if you have specific use-cases that could be documented.
