### ISSUE TITLE
Logging to file

### ISSUE THREAD

**Issue by Offerel** [sabre-io/dav#1156]
How can I log login errors to a log file?

I have tried to add the following to my server.php, but it doesn't work. 

```
$server->exec();

$server->on('exception', function(Exception $e) {
	if ($e instanceof \Sabre\DAV\Exception\NotAuthenticated) {
		myErrorHandler("test");
	}
});
```
Btw: myErrorHandler() saves successfully to a textile, but it doesn't execute when wrong credentials are entered.

**Comment by evert** [comment]
Event handlers need to be setup before calling `->exec()`. All the actual work is done within `->exec()` so you're a bit too late.

**Comment by staabm** [comment]
would it make sense we throw an exception when `on()` is called after `exec()` was already called?

**Comment by Offerel** [comment]
Ahh. Ok. I have changed it to:

```
$server->on('exception',function(Exception $e) {
	myErrorHandler(1, get_class($e).": ".$e->getMessage().", status: ".$e->getHTTPCode().", client: ".$_SERVER['REMOTE_ADDR'].", server: ".$_SERVER['SERVER_NAME'],0,0);
});

$server->exec();
```

This produces a log file with the following: 

```
2019/06/07 14:44:00 [error] Sabre\DAV\Exception\NotAuthenticated: No 'Authorization: Digest' header found. Either the client didn't send one, or the server is misconfigured, status: 401, client: 84.58.74.55, server: dav.myserver.com
```
