### ISSUE TITLE
Remove username from url 

### ISSUE THREAD

**Issue by Offerel** [sabre-io/dav#1157]
Currently when I access a calendar or addressbook in sabredav, the url contains always the username. For example 
```
https://dav.example.com/calendars/<username>/default/
```

I wonder if it is possible to use a url without the username and stripping it from the url. Since I use nginx as webserver, maybe with some rewrite rule. I have no skills in using regex or rewrites, but maybe someone can give me some examples.

**Comment by OpenSysJoe** [comment]
At first glance it looks like an internal rewrite of the URI would do. Like rewrite
```
/calendars/default/
```
to
```
/calendars/%{REMOTE_USER}/default/
```
But there's a bit more work ahead.

Authentication is triggered by the framework by responding with status 401 and corresponding `WWW-Authenticate` headers when an unauthenticated request for an existing resource is received. If the initial URI doesn't contain a username, the framework cannot identify the requested resource and will respond with a NotFound exception instead (or even worse: imagine your calender name references another principal). So, the rewrite rule is essential and has to be executed before the request is passed on to the framework.

For the rewrite rule to be able to insert `%{REMOTE_USER}`, you would have to configure your web server to do the authentication using the Sabre database for validation of the credentials. I don't know how to do this with nginx (sorry). For Apache I would use mod_authnz_external and a tiny script for accessing the database and validating the credentials.

From this point on, the framework only receives requests containing a valid `Authorization` header and only referencing resources owned by the authenticated `${REMOTE_USER}`. This should prevent it from ever requesting authentication on its own.

Beware: I didn't take too much time to look at the code, so maybe there are further pitfalls. Also, I never tested this kind of setup (but it really sounds like a great idea BTW).

**Comment by Offerel** [comment]
I have used http with nginx before. That's why it authenticates before it entered the directory. But now I will to switch to digest auth with PDO, so authentication is made after entered the directory.

**Comment by evert** [comment]
Rewrites will not work. To do this you will need to create your own versions of the principal and calendar nodes. Probably not a very easy thing to do.

**Comment by Offerel** [comment]
Ok. That's currently out of my scope. Maybe that's a later project but only in a far future. Or someone else can do that. 

My only concern with the current approach is, that the username is visible in some external logfiles.

**Comment by evert** [comment]
Your best option is to not rewrite anything, but to change the authentication plugin to use a different string for the principal path and username. This is by far the easiest solution.

I wish you offered your motivation right from the start, because this is actually quite easy to achieve and would have saved everyone some time. Pretty typical XY problem.
