### ISSUE TITLE
defaultUsernamePath not working

### ISSUE THREAD

**Issue by flowthentic** [sabre-io/dav#1158]
Hello, setting the
```
$aclPlugin = new \Sabre\DAVACL\Plugin();
$aclPlugin->defaultUsernamePath = 'principals/users';
```

Doesn't work for me in version 3.2. I get error that user jakub does not exist.
For me it looks like the property is nowhere tested, as `grep` finds only the one line where I efine it:

```
uid1121635@shellserver:~/.../sub/sabre$ grep -Ri "usernamepath" .
./common_init.php:$aclPlugin->defaultUsernamePath = 'principals/users';
```
If I create a principal with uri `principals/jakub` instead of `principals/users/jakub`, everything goes smooth.
Is there some step I am missing?

**Comment by evert** [comment]
Changing 'defaultUsernamePath' does not automatically change where users are stored, it changes where users are *found*.

Using this setting only makes sense if you define your own principals tree. Once the principals tree is set up, and all your real users are stored under `/principals/users/[foo]`, change this setting.
