### ISSUE TITLE
Drop PHP7.0 and PHP7.1

### ISSUE THREAD

**Issue by DeepDiver1975** [sabre-io/dav#1167]
refs https://www.php.net/supported-versions.php

We can/should drop support for php7.0 and/or php7.1

How are we dealing with dav version (and versions in other sabre libs as well)?

4.0 -> marked end of 5.x
4.1 -> end of 7.0
4.2 -> end of 7.1

Or do we need major versions each?

5.0 which drops 7.0 and 7.1

@staabm @evert

**Comment by staabm** [comment]
IMO we can drop php versions with minor releases in case we define them in composer.json etc.

**Comment by evert** [comment]
Personally if you don't want to support these versions, I would drop them both at once and stop maintaining the 4.0 branch asap. People who need support for older versions can still go to 3.x. 

Maintaining all these different branches just creates more work for yourself. Calling it 4.1 or 5.0 doesn't make a huge difference imho although 5.0 would be more correct if you want to use semantic versioning going forward

**Comment by DeepDiver1975** [comment]
so let's aim for 5.0 with php 7.2, 7.3 and 7.4.
6.0 might be worth to think about once php8 is about to arrive.

I'll have a closer look at the other libraries as well these days.

THX

**Comment by DeepDiver1975** [comment]
7.0 is already removed - 7.1 will follow - no need to keep this ticket open
