### ISSUE TITLE
Upgrading to 4.0

### ISSUE THREAD

**Issue by e-dschungel** [sabre-io/dav#1170]

**Comment by DeepDiver1975** [comment]
A Blog Post will come to describe the Upgrade process

**Comment by quicktrick** [comment]
@DeepDiver1975 , please, publish your blog post, I'm waiting for it eagerly.  I have a few working installations of v.3.2.2, 3.2.3, but I cannot get v.4.0.0 to work properly. The examples do not work, except `minimal.php`.  Thank you very much in advance!

**Comment by evert** [comment]
@quicktrick can you open a new ticket explaining which examples don't work and what the symptoms are? You might have found a bug

**Comment by quicktrick** [comment]
Hi @evert !  I'll do it a little later, I've already replaced v.4.0.0 with v.3.2.3 on that server.  I'll be able to make a new v.4.0.0 installation in about a week.  Thanks a lot for your reply!
