### ISSUE TITLE
Upgrade to 4.0

### ISSUE THREAD

**Issue by Offerel** [sabre-io/dav#1171]
How can upgrade to 4.0 from 3.2? I tried to follow the instructions at http://sabre.io/dav/install/ with the manual install but i failed. Could you please provide instructions for a manual installation/upgrade?

**Comment by DeepDiver1975** [comment]
1. user composer
2. upgrade your dependencies with composer
3. run your test suite
4. see where it failes
5. fix it ;-)

see https://github.com/sabre-io/dav/issues/1170#issuecomment-508946845 - there is a blog post to come .....

**Comment by Offerel** [comment]
In that case, something is broken. I can use any URL which is not the root URL of sabredav but if use the browser i run in to the same problem as in #1169 . Sabredav is installed in a Nginx sub-directory in my case.

Maybe, i have done something wrong, im not really sure. I haven't used composer before.

**Comment by Offerel** [comment]
Maybe i found a dirty fix. If i remove `declare(strict_types=1);` from TemporaryFileFilterPlugin.php, i get it to work. But i think this should be only a workaround.

**Comment by ByteHamster** [comment]
@Offerel Yesterday, my change was merged that should fix this issue. Could you please check again with the current master branch?

**Comment by ByteHamster** [comment]
I just confirmed that the issue in `TemporaryFileFilterPlugin` is present on 4.0.0 but no longer on master.

**Comment by Offerel** [comment]
sorry was on vacation without any internet access the last weeks. I updated now to 4.0.1 and can confirm that my issues are truly fixed. Many thx for this.
