### ISSUE TITLE
Problem on IIS

### ISSUE THREAD

**Issue by SilverSnake83** [sabre-io/dav#1172]
Hi

During our development for a Canon MFP web application we stumbled on an issue.
Our server is IIS 10 and running php 7.3.

SabreDav is working perfectly on nginx server with windows client or MFP client.
But on IIS we seem to have an issue.
On windows client we can do everything fine. Write a file, move a file, delete a file. 
But on the MFP we have an issue for uploading a file to the IIS. The MFP is correclty login in the webdav but cannot write the file.

After some digging on the low level of the PUT request we found out that the MFP client is sending the file with the "Transfer-Encoding: chunked" header.
I created a curl PUT request to test it out :

`curl -X PUT -H "Content-Type:" -H "Transfer-Encoding: chunked" -d "@C:\document.pdf" http://admin:password@192.168.1.125:8000/api/module/dav/web/c.txt`

And this request is working on nginx but not on IIS.
From my point of view it seems like IIS is not treating the chunked type of request correctly and therefore IIS is not fully compatible with SabreDAV.

Has anyone ever experienced that?

**Comment by evert** [comment]
Hi, I haven't heard a lot of people run IIS in the last 10 years or so, but it's not surprising they don't support chunked transfer encoding in request bodies. This was traditionally a big issue with a bunch of servers, but many of them have slowly been fixed over time.

**Comment by SilverSnake83** [comment]
I've seens some people saying that IIS is handling that type of request. It seems true as I cannot seem to find anything with google which is the main reason why  I created this issue.
The fact that we are in 2019 and IIS still doesn't handle that type of request is a bit strange to me.
Nobody tried to run SabreDAV with IIS before?

**Comment by evert** [comment]
IIS is not a very popular webserver, and I would say very unpopular for typical PHP applications. So this doesn't really surprise me. I would say that there were more people running on IIS 10 years ago, but it's so much easier to just run Linux in a VM these days.

**Comment by SilverSnake83** [comment]
Alright I managed to get around that impossibility. Besides this chunked upload everything is working fine with IIS. 
Maybe the SabreDAV team should edit this page (http://sabre.io/dav/webservers/) to warm users about that.
Thank you I close this issue.
