### ISSUE TITLE
No autoload.php

### ISSUE THREAD

**Issue by nolash** [sabre-io/dav#1173]
According to [Getting Started](http://sabre.io/dav/gettingstarted/) section in the docs, the `autoload.php` file should be found thus:

> If you used the zip, it will be where ever you unpacked the zip.

I've tried the `4.0.0` zip and `git` commit `e03a2637ba21835c26e8c9745fd2720e2713f564` ... and there is no `vendor` dir or any `autoload.php` file anywhere in the tree.

**Comment by DeepDiver1975** [comment]
Which zip did you grab? From here?
![Screenshot from 2019-07-26 08-45-49](https://user-images.githubusercontent.com/1005065/61931737-cdce4480-af81-11e9-99f4-74423675cb3d.png)

This gives you only the source code.

Please use composer to install sabre dav and it's dependencies. THX

**Comment by nolash** [comment]
> Please use composer to install sabre dav and it's dependencies. THX

That means that the second alternative for install described in the installation readme does no longer apply?

**Comment by nolash** [comment]
With `composer` I'm only able to build if I clone repo master and build using `composer require sabre/dav dev-master`. The command in install docs (`~3.2.0`) fails due to failing version dep `sabre/event`, and if I use the `4.0.0` release link neither `3.2.0` `4.0.0` `master` or `dev-master` succeed. Never used this tool before, maybe it's to be expected, dunno. Let me know if logs are desired.

Happens with:
* `Composer version 1.8.6 2019-06-11 15:03:05` / `PHP 7.3.7 (cli) (built: Jul  3 2019 13:55:48) ( NTS )`
* `Composer version 1.7.2 2018-08-16 16:57:12` / `PHP 7.2.20 (cli) (built: Jul 23 2019 18:49:07) ( NTS )`

**Comment by DeepDiver1975** [comment]
https://github.com/sabre-io/dav/releases/tag/3.2.2 was the last version where we shipped the zip.
No body since then asked for it - so yes: we no longer provide the zips. Everybody uses composer these days.

We shall update the documentation - thanks for the hint.

**Comment by DeepDiver1975** [comment]
No idea what exactly you are doing - please try to understand how composer works.

```sh
$ composer require sabre/dav
Using version ^4.0 for sabre/dav
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 7 installs, 0 updates, 0 removals
  - Installing psr/log (1.1.0): Loading from cache
  - Installing sabre/uri (2.1.2): Loading from cache
  - Installing sabre/event (5.0.3): Loading from cache
  - Installing sabre/http (5.0.0): Loading from cache
  - Installing sabre/xml (2.1.2): Downloading (100%)         
  - Installing sabre/vobject (4.2.0): Loading from cache
  - Installing sabre/dav (4.0.0): Loading from cache
sabre/vobject suggests installing hoa/bench (If you would like to run the benchmark scripts)
sabre/dav suggests installing ext-imap (*)
Writing lock file
Generating autoload files

**Comment by nolash** [comment]
Yes, I think I understand what it does.

The [http://sabre.io/dav/install/](docs) say specify a version hint in the install doc:

`composer require sabre/dav ~3.2.0`

Above, you are not:

`composer require sabre/dav`

Anyway, on my system I get this with when I do the latter:

```
$ composer require sabre/dav
Using version ^4.0 for sabre/dav
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package sabre/dav No version set (parsed as 1.0.0) is satisfiable by sabre/dav[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```
