### ISSUE TITLE
Configure Sabre to read mysql Calendars 

### ISSUE THREAD

**Issue by winnertako** [sabre-io/dav#1176]
Hello, 

I'm trying to setup my sabredav to work with the kolab 16 roundcube plugin but without success.

I can't make my sabredav read my calendars created on rondcube side. I think is missing some configuration on my sabredav .

Can someone help me?

Thank you

**Comment by evert** [comment]
This doc mainly goes into that topic:

http://sabre.io/dav/caldav-carddav-integration-guide/

**Comment by winnertako** [comment]
Thank you evert. 

I'm a little confused.

So I have to create a new structures on my mysql database or I can use the existing provided by the roundcube?

**Comment by evert** [comment]
If you are trying to run a sabredav instance that uses data from custom datasources, then you need to write your own backend classes to make these connections.

If I recall correctly roundcube might already have some caldav/carddav support though, so maybe you don't have to write this.
