### ISSUE TITLE
Scheduling does not work as expected

### ISSUE THREAD

**Issue by pk1234** [sabre-io/dav#1179]
Hi everybody

thanks very much for this wonderful software. We use SabreDAV 3.2.2 in production for many years now and like it very much. In particular we were able to write our own backend that connects SabreDAV with our own user management and let our user authenticate against SabreDAV with their smart cards.

Scheduling did not work perfectly and we ignored that. But during the last weeks I finally found the time to debug the problem.

Here's what happening:
- Users A, B, C and D are all internal users
- User A creates a new calendar event (with Thunderbird-Lightning but that does not matter). A is the organizer and B, C and D are participants
- SabreDAV will create two calendarobjects: one in the calendar of A and another one in the calendar of B
- no calendarobjects will be created in the calendars of C or D
- SabreDAV will send emails to B, C and D. If B accepts the invitiation the status of the already existing calendarobject will be changed. If C or D accept the invitation new calendarobjects in their calendars will be created.

Here's what I found out so far:

scheduleLocalDelivery from the CalDAV scheduling plugin is called three times, namely for users B, C and D. When it is called for user B it will create a new calendarobject in the calendar of user B. When called for any further user scheduleLocalDelivery will check wether a calendarobject does already exist and will find the calendarobject that was created within the calendar of user B. Therefor it does not create a new calendarobject in the calendar of user C or D but instead updates the calendarobject of user B.

Here's the relevant part of scheduleLocalDelivery:

        // Next, we're going to find out if the item already exits in one of
        // the users' calendars.
        $uid = $iTipMessage->uid;

        $newFileName = 'sabredav-' . \Sabre\DAV\UUIDUtil::getUUID() . '.ics';

        $home = $this->server->tree->getNodeForPath($homePath);
        $inbox = $this->server->tree->getNodeForPath($inboxPath);

        $currentObject = null;
        $objectNode = null;
        $isNewNode = false;

        $result = $home->getCalendarObjectByUID($uid);
        if ($result) {
            // There was an existing object, we need to update probably.
            $objectPath = $homePath . '/' . $result;
            $objectNode = $this->server->tree->getNodeForPath($objectPath);
            $oldICalendarData = $objectNode->get();
            $currentObject = Reader::read($oldICalendarData);
        } else {
            $isNewNode = true;
        }

getCalendarObjectByUID(c868ed-.....) will return false when called for user B since there is no entry within the tree calendars/B/ with the given UID. But when called again for user C or D getCalendarObjectByUID() will return B/sabre-some-uid.

This is because calendars/B/default, calendars/C/B/ and calendars/D/B/ are three instances of the calendar of user B. This is managed by our calendar-backend. Read/Write-permissions on calendars are controlled outside of sabredav. Whenever a new users is added to our central database our calendar-backend will create a new calendar in table calendars and a new calendarinstance in table calendarinstances with access=1 and uri=default. If User A has read or write permissions for the calendar of user B another calendarinstance is autocreated for user A with access=2 or 3 and uri=B.

So scheduleLocalDelivery should not test whether a calendarobject with the given UID exists in one of C or D calendarinstances but it should restrict the search to the callendarinstance of C or D with access=1.

I was tempted to change

        $homePath = $result[$caldavNS . 'calendar-home-set']->getHref();

to

        $homePath = $result[$caldavNS . 'calendar-home-set']->getHref() . 'default/;

but this caused the following error-message:
Call to undefined method Sabre\\CalDAV\\SharedCalendar::getCalendarObjectByUID()

Another option would be to add a second parameter to getCalendarObjectByUID()

Any ideas or comments on how I should proceed?

Kind regards

Peter Koch

**Comment by DeepDiver1975** [comment]
Transfered to the dav repo - this fits better.

**Comment by pk1234** [comment]
I'm getting closer:

Look at the last lines of vendor/sabre/dav/lib/CalDAV/CalendarHome.php

    /**
     * Searches through all of a users calendars and calendar objects to find
     * an object with a specific UID.
     *
     * This method should return the path to this object, relative to the
     * calendar home, so this path usually only contains two parts:
     *
     * calendarpath/objectpath.ics
     *
     * If the uid is not found, return null.
     *
     * This method should only consider * objects that the principal owns, so
     * any calendars owned by other principals that also appear in this
     * collection should be ignored.
     *
     * @param string $uid
     * @return string|null
     */
    function getCalendarObjectByUID($uid) {

        return $this->caldavBackend->getCalendarObjectByUID($this->principalInfo['uri'], $uid);

    }

Seems like getCalendarObjectByUID($uid) is supposed to find only those calendar objects that the principal owns (i.e. access=1). Our calendar-backend is a copy of the PDO-backend and routine getCalendarObjectByUID($principaluri,$uid) was not modified.

So the problem seems to be within the PDO-backend and I can fix it within our own calendar-backend.

Peter

**Comment by stratmaster** [comment]
Does this issue have something to do with the one in #1026? For the latter there is a pull request pending (#1032).

**Comment by pk1234** [comment]
Hi stratmaster

this problem is caused by the exact same bug as in #1026 and I fixed it by replacing
```
    $query = <<<SQL
SELECT
    calendar_instances.uri AS calendaruri, calendarobjects.uri as objecturi
FROM
    $this->calendarObjectTableName AS calendarobjects
LEFT JOIN
    $this->calendarInstancesTableName AS calendar_instances
    ON calendarobjects.calendarid = calendar_instances.calendarid
WHERE
    calendar_instances.principaluri = ?
    AND
    calendarobjects.uid = ?
SQL;
```
with
```
    $query="select i.uri calendaruri, o.uri objecturi from calendarobjects o, calendarinstances i ".
            "where o.calendarid = i.calendarid ".
              "and i.principaluri = ? ".
              "and i.access = 1 ".
              "and o.uid = ?"
    ;
```
in my calendar-plugin. So the same fix should be applied to vendor/sabre/dav/lib/CalDAV/Backend/PDO.php

And this is exactly the same fix as in #1032. It restricts the search for calendarobjects with the given UID to those calendarinstances of the given principal that are owned by that principal.

I did a couple of tests today and this works.

I also searched through the complete sabre source for occurences of getCalendarObjectByUID. It is used only once in CalDAV/Schedule/Plugin.php. So the above fix will have no unwanted side effects.

Peter

**Comment by stratmaster** [comment]
I've just made a pull request (#1181), which adresses this issue.

**Comment by keunes** [comment]
Since #1881 is merged, shouldn't this issue be closed?

**Comment by phil-davis** [comment]
> Since #1881 is merged, shouldn't this issue be closed?

Yes, looks like it was in release 4.0.3
