### ISSUE TITLE
Acceptance of invite does not get picked up by Calendar on macOS

### ISSUE THREAD

**Issue by tchapi** [sabre-io/dav#1180]
Hello there

The problem I have relates to Baikal but I open an issue here because I think it deals with the underlying sabre/dav implementation itself, and maybe someone else ran into the same problem or something similar.

So I've set up my own Baikal server, based on sabre/dav, on which I have a single user : `user@domain.com`.
Everything is working fine, **except** replies to invitations.

This looks like https://github.com/sabre-io/dav/issues/556 but not exactly, and is the same as this SO question (_not answered_) : https://stackoverflow.com/questions/55784536/what-is-the-expected-behavior-of-caldav-recipient-acceptance

I'm posting this here more as a question since I don't know exactly where to look for debug.

Here is what happens :
--

Using Calendar on a Mac (macOS X 10.14.4 FWIW) :

  1. I create an event as `user@domain.com`, I add `attendee@gmail.com` as an **ATTENDEE**
  2. `attendee@gmail.com` receives an email from my server with a `calendar.vcs` file

Invitation (`calendar.vcs`) received by `attendee@gmail.com` : 

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 4.2.0//EN
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:Europe/Paris
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
DTSTART:19810329T020000
TZNAME:CEST
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
DTSTART:19961027T030000
TZNAME:CET
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
TRANSP:OPAQUE
DTEND;TZID=Europe/Paris:20190814T151500
DTSTART;TZID=Europe/Paris:20190814T141500
ORGANIZER;CN=Myself:mailto:user@domain.com
UID:CB337B3E-B900-4A87-904D-BE86228B1435
DTSTAMP:20190812T192058Z
SEQUENCE:0
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
SUMMARY:ThisIsATestEvent
LAST-MODIFIED:20190812T192057Z
CREATED:20190812T192045Z
ATTENDEE;CN=Attendee;CUTYPE=INDIVIDUAL;EMAIL=attendee@gmail
 .com;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:mailto:attendee@gmail.com
ATTENDEE;CN=Myself;CUTYPE=INDIVIDUAL;EMAIL=user@domain.com;PARTSTAT=ACCEPTED;
 ROLE=CHAIR:mailto:user@domain.com
END:VEVENT
END:VCALENDAR
```
  3. on Google Calendar (_or via the received mail_), the attendee answer 'YES' to the invitation
  4. `user@domain.com` receives an acceptance email from Google, with a `invite.ics` file

Reply (acceptance, `invite.ics`) received by `user@domain.com` : 

```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REPLY
BEGIN:VEVENT
DTSTART:20190814T121500Z
DTEND:20190814T131500Z
DTSTAMP:20190812T192255Z
ORGANIZER;CN=Myself:mailto:user@domain.com
UID:CB337B3E-B900-4A87-904D-BE86228B1435
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=attendee
 @gmail.com;X-NUM-GUESTS=0:mailto:attendee@gmail.com
CREATED:20190812T192058Z
DESCRIPTION:
LAST-MODIFIED:20190812T192253Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:ThisIsATestEvent
TRANSP:OPAQUE
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
END:VEVENT
END:VCALENDAR
```

The problem is that the PARTSTAT part of the event on my server is never updated to reflect the **ACCEPTED** status. Even when I open the `invite.ics` with the Calendar app file that is sent back where the PARTSTAT is clearly indicated.

I even tried to open the `invite.ics` reply with other clients, such as DavX (Android) and the Android Calendar app.

I don't know where is the culprit. Is it the formatting of the `invite.ics` from Google ? Is this the original `calendar.vcs` file from my Baikal installation ? Is this a known bug of Calendar on macOS X that create buggy events ?

Happy to test further or provide logs/etc if needed.
Any hint is appreciated ;)

BR,

**Comment by tchapi** [comment]
Anyone ? 😢

**Comment by tchapi** [comment]
Hello
Has anyone a hint or idea on what could be the problem here ? I can't wrap my mind around this issue, and I may be misinterpreting the CalDAV rfc as to what should happen in this case.

Thanks !

**Comment by staabm** [comment]
No idea, sorry

**Comment by evert** [comment]
Same here.. i just don't know. Best might be to file an apple bug instead, as it's likely that the problem is there. I don't think the IMIP stuff in Apple Mail/Calendar ever worked particularly well.

**Comment by evert** [comment]
Actually.. one thing is super suspicious. Looks like timezones are stripped from the second event. This *could* explain it. You could try manually setting correctly to 'Europe/Paris' and see if if behaves correctly

**Comment by tchapi** [comment]
Hmmm ok, I'll try that, it's worth a shot. Thanks !

**Comment by tchapi** [comment]
... and unfortunately it's not that.

**Comment by apollo-sturdy** [comment]
Hey @evert. Curious why you closed this issue? Seems like it's still a problem. Did anyone get it to work?

**Comment by evert** [comment]
As per my last comment in this thread, this is likely just an apple bug.

**Comment by apollo-sturdy** [comment]
> As per my last comment in this thread, this is likely just an apple bug.

Sorry, I thought you changed your mind on this as your last comment says otherwise. Also seems unlikely as OP had the same problem with "DavX (Android) and the Android Calendar app"?
