### ISSUE TITLE
Word 2014 builds greater than 1812 problems saving documents

### ISSUE THREAD

**Issue by Ninpo** [sabre-io/dav#1188]
Hi,

First of all thanks for the great work, we've used Sabre DAV for years.

Builds of Word 2014 since version 1812 (so 1900+) exhibit peculiar behaviour with documents accessed via Sabre DAV. Opening a document and immediately editing/saving works fine. However if you allow the document to idle for a period of time (45s+), when you "wake" Word up it issues a GET and a PROPFIND, after which point any attempted saving fails with no PUT request ever sent to the server.

If Word is not allowed to idle, the problem does not arise.

After inspecting the traffic between Word and Server, the GET retrieves the entire document again and the propfind contains:
```XML
<?xml version="1.0" ?>
<D:propfind xmlns:D="DAV:" xmlns:Office="urn:schemas-microsoft-com:office:office">
        <D:prop>
                <D:creationdate/>
                <D:getlastmodified/>
                <D:getcontentlength/>
                <Office:modifiedby/>
        </D:prop>
</D:propfind>
```

With the response:

```XML
<?xml version="1.0" ?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
        <d:response>
                <d:href>/Instruction_Letter.doc</d:href>
                <d:propstat>
                        <d:prop>
                                <d:getlastmodified>Tue, 20 Aug 2019 14:07:42 GMT</d:getlastmodified>
                                <d:getcontentlength>36472</d:getcontentlength>
                        </d:prop>
                        <d:status>HTTP/1.1 200 OK</d:status>
                </d:propstat>
                <d:propstat>
                        <d:prop>
                                <d:creationdate/>
                                <x1:modifiedby xmlns:x1="urn:schemas-microsoft-com:office:office"/>
                        </d:prop>
                        <d:status>HTTP/1.1 404 Not Found</d:status>
                </d:propstat>
        </d:response>
</d:multistatus>
```

We've tried adding the PropertyStorage backend and added values so that they get populated in case that was upsetting Word, but in case something more complicated than "Firstname Surname" is needed for the modifiedby property, that does not appear to be the case.

We've stripped everything back to a completely bare SabreDAV 4.0.1 install using PDO for Locks and PropertyStorage with an sqlite file:

```php
<?php

use
    Sabre\DAV;

// The autoloader
require 'vendor/autoload.php';

// Now we're creating a whole bunch of objects
$rootDirectory = new DAV\FS\Directory('public');

// The server object is responsible for making sense out of the WebDAV protocol
$server = new DAV\Server($rootDirectory);

// If your server is not on your webroot, make sure the following line has the
// correct information
//$server->setBaseUri('/server.php');

// The lock manager is reponsible for making sure users don't overwrite
// each others changes.
//$lockBackend = new DAV\Locks\Backend\File('data/locks');
$lockspdo = new PDO('sqlite:data/locks.sqlite');
$propspdo = new PDO('sqlite:data/properties.sqlite');
$locksBackend = new DAV\Locks\Backend\PDO($lockspdo);
$lockPlugin = new DAV\Locks\Plugin($locksBackend);
$storageBackend = new DAV\PropertyStorage\Backend\PDO($propspdo);
$propertyStorage = new DAV\PropertyStorage\Plugin($storageBackend);
$server->addPlugin($lockPlugin);
$server->addPlugin($propertyStorage);

// This ensures that we get a pretty index in the browser, but it is
// optional.
$server->addPlugin(new DAV\Browser\Plugin());

// All we need to do now, is to fire up the server
$server->exec();
```

So reaching out to you good folks to see if you have any suggestions. We've set hideLockRoot to true as noted in one of the other Office compatibility notes in the docs but that doesn't appear to affect anything.

Many thanks

**Comment by evert** [comment]
This is a shot in the dark, but could you also try `FSExt/Directory` instead of plain `Directory`. It has a few more features that *might* help. In particular I'm thinking it has ETag support, and maybe Word will like that better.

Other than that, I don't have any real ideas. I usually spent a lot of time getting new Office clients to work, and usually my process (lacking detailed error messages) is:

1. Get a working WebDAV server, like apache mod_dav
2. Get Sabre/dav alongside
3. Keep modifying sabre/dav until it matches the other client in every detail and see which change cause things to work.
4. Roll back all the other changes I made, keep the 1 hack for Office and see if it still works. If not, go back to 3.

This is for example how I discovered that Windows XP requires a newline after the end of PROPFIND XML responses (granted it took me days to spot this)

**Comment by Ninpo** [comment]
> This is a shot in the dark, but could you also try `FSExt/Directory` instead of plain `Directory`. It has a few more features that _might_ help. In particular I'm thinking it has ETag support, and maybe Word will like that better.
> 
> Other than that, I don't have any real ideas. I usually spent a lot of time getting new Office clients to work, and usually my process (lacking detailed error messages) is:
> 
>     1. Get a working WebDAV server, like apache mod_dav
> 
>     2. Get Sabre/dav alongside
> 
>     3. Keep modifying sabre/dav until it matches the other client in every detail and see which change cause things to work.
> 
>     4. Roll back all the other changes I made, keep the 1 hack for Office and see if it still works. If not, go back to 3.
> 
> 
> This is for example how I discovered that Windows XP requires a newline after the end of PROPFIND XML responses (granted it took me days to spot this)

FSExt Directory backend did the trick!

Thanks ever so much.
