### ISSUE TITLE
Can I change template for sending invite email?

### ISSUE THREAD

**Issue by thovt93** [sabre-io/dav#1189]
I want to change template when I send invite email. Can I do that?

**Comment by ByteHamster** [comment]
Instead of adding the `IMipPlugin` to your server, you can extend `Sabre\CalDAV\Schedule\IMipPlugin` and add your own code. Easiest would be to just overrrite the `IMipPlugin::mail()` function

**Comment by thovt93** [comment]
Okey thank you so much!
