### ISSUE TITLE
Matomo encountered an error: Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by pranab155** [sabre-io/dav#1192]
Fatal error: Maximum execution time of 30 seconds exceeded in /apache/apache2.4/httpd-2.4.25/htdocs/matomo/core/DataTable.php on line 355
Matomo encountered an error: Maximum execution time of 30 seconds exceeded (which lead to: A fatal error occurred.)

Please help to resolve the issue i am using 
MATOMO- 3.10
Apache: apache2.4
php: PHP Version 7.2.13

**Comment by staabm** [comment]
Sounds like you are hitting endless loop. Could you describe how we can reproduce the problem? Which client do you use? Which version of sabre/dav do you use

**Comment by evert** [comment]
If you are a user of matamo, please report a bug there, not here. If there is a bug in vobject, leave it up to the matamo developers to report it here. We don't give support to software not written by us.
