### ISSUE TITLE
TBSYNC - baikal settings error

### ISSUE THREAD

**Issue by hlvs44** [sabre-io/dav#1195]
Upgrading baikal to 0.6.0-1 version I met some problems in thunderbird syncronization via tbsync. This is the reponse of tbsync developers.
I can provide some screenshots if needed.
Thanks a lot.

Il 28/09/19 09:28, John Bieling ha scritto:
>
>   <s:message>explode() expects parameter 2 to be string, null given</s:message>
>
> ****That looks like a bug in baikal.** You have all the information needed to file a bug at baikal (request and response).**
>This is the error found trying to add the account, now working good with evolution mail client:
> Best regards,
>
> John
> On 28.09.2019 09:03, xxxx wrote:
>>
>> Hallo,
>>
>> baikal is a light server for caldav and cardav data.
>>
>> **This is the error found trying to add the account, now working good with evolution mail client:**
>>
>>
>> -----------------------------------------------------------
>>
>> URL:
>> http://localhost:81/dav.php/calendars (PROPFIND)
>>
>> Request:
>> <d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>
>>
>> Response:
>> <?xml version="1.0" encoding="utf-8"?>
>> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
>>   <s:sabredav-version>4.0.1</s:sabredav-version>
>>   <s:exception>TypeError</s:exception>
>>   <s:message>explode() expects parameter 2 to be string, null given</s:message>
>> </d:error>
>>
>> -----------------------------------------------------------
>>
>> URL:
>> http://localhost:81/dav.php/addressbooks (PROPFIND)
>>
>> Request:
>> <d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>
>>
>> Response:
>> <?xml version="1.0" encoding="utf-8"?>
>> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
>>   <s:sabredav-version>4.0.1</s:sabredav-version>
>>   <s:exception>TypeError</s:exception>
>>   <s:message>explode() expects parameter 2 to be string, null given</s:message>
>> </d:error>
>>
>>

**Comment by DeepDiver1975** [comment]
duplicate #1194 and others .... needs a new sabre/dav release
