### ISSUE TITLE
Plugin Browser : Guess Content Type doesn't work when setBaseUri is set with on a folder and not a php file

### ISSUE THREAD

**Issue by gloony** [sabre-io/dav#1200]
When the setBaseUri is set without a name file (without index.php for exemple) and directly on a folder, the script crash with the following error :

```
4.0.2 TypeError strrpos() expects parameter 1 to be string, null given
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>4.0.2</s:sabredav-version>
<s:exception>TypeError</s:exception>
<s:message>
strrpos() expects parameter 1 to be string, null given
</s:message>
<s:message>...</s:message>
</d:error>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">...</d:error>
```

I found the url more beauty without that and I achieve it with old version of sabre-dav.
I don't know whom file give me the error I don't have log of this error only this display.

When you enter a subdirectoy after the url, all work fine, but then you cannot acced with a standard client.

**Comment by DeepDiver1975** [comment]
Do you have the stack trace of the exception at hand? Maybe in the apache error log or somewhere ... THX

**Comment by gloony** [comment]
I tested on two server with the same problem, but I don't have any log on my apache dir.
Even if I try to change the path log before set sabre-dav.

I don't see on the documentation if it is possible to have a "debug" mode to display full error message but I failed to find it.

**Comment by gloony** [comment]
Sorry, I do some dirty work and disable the try catch on lib/DAV/Server.php (function start). And I finally got the original message : 

```
Fatal error: Uncaught TypeError: strrpos() expects parameter 1 to be string, null given in /plugin/sabre-dav4/lib/DAV/Browser/GuessContentType.php:89
Stack trace:
#0 /plugin/sabre-dav4/lib/DAV/Browser/GuessContentType.php(89): strrpos(NULL, '.')
#1 /plugin/sabre-dav4/lib/DAV/Browser/GuessContentType.php(75): Sabre\DAV\Browser\GuessContentType->getContentType(NULL)
#2 /plugin/sabre-dav4/lib/DAV/PropFind.php(96): Sabre\DAV\Browser\GuessContentType->Sabre\DAV\Browser\{closure}()
#3 /plugin/sabre-dav4/lib/DAV/Browser/GuessContentType.php(76): Sabre\DAV\PropFind->handle('{DAV:}getconten...', Object(Closure))
#4 /plugin/sabre-dav4/vendor/sabre/event/lib/WildcardEmitterTrait.php(96): Sabre\DAV\Browser\GuessContentType->propFind(Object(Sabre\DAV\PropFind), Object(WorldeskDAV\HomeCollection))
#5 /home/httpd/vhost in /plugin/sabre-dav4/lib/DAV/Browser/GuessContentType.php on line 89
```
