### ISSUE TITLE
Location URLs

### ISSUE THREAD

**Issue by dolanor** [sabre-io/dav#1202]
Hi,

I use Nextcloud 15 and I try to add 2 URLs to a Location. A `geo:` url for GPS, and a http link to some [OSM way](https://www.openstreetmap.org/way/) to show a specific room in a building. But once I sync it with the [caldav-go](https://github.com/dolanor/caldav-go) client, it only shows in the ics file with the first ALTREP I set, the second one is ignored. 

If I know how to read the RFC, it seems it could be a list. (at least, that's what the creator of the lib client exposed in the API).

https://github.com/sabre-io/SabreDAV/blob/master/docs/rfc6321.txt#L2166

Any idea?

**Comment by evert** [comment]
Given that you're using nextcloud, can you log a bug there first. It's possible that it's a sabre/dav or sabre/vobject issue, but if you can't prove it please start with a bug report @ the software that you're using.
