### ISSUE TITLE
SSL r ead: error:00000000:lib(0):func(0):reason(0), errno 104

### ISSUE THREAD

**Issue by vaajnur** [sabre-io/dav#1206]
Fatal error: Uncaught exception 'Sabre\HTTP\ClientException' with message 'SSL r
ead: error:00000000:lib(0):func(0):reason(0), errno 104' in /home/d/dnkayuqs/php
-webdav/vendor/sabre/http/lib/Client.php:356
Stack trace:
#0 /home/d/dnkayuqs/php-webdav/vendor/sabre/http/lib/Client.php(103): Sabre\HTTP
\Client->doRequest(Object(Sabre\HTTP\Request))
#1 /home/d/dnkayuqs/php-webdav/vendor/sabre/dav/lib/DAV/Client.php(373): Sabre\H
TTP\Client->send(Object(Sabre\HTTP\Request))
#2 /home/d/dnkayuqs/php-webdav/index_copy.php(78): Sabre\DAV\Client->request('PU
T', 'dnkayuqs_backup...', Resource id #43)
#3 {main}
  thrown in /home/d/dnkayuqs/php-webdav/vendor/sabre/http/lib/Client.php on line
 356

**Comment by vaajnur** [comment]
small files are submited, but large files (>2GB) return this error.

**Comment by DeepDiver1975** [comment]
SSL error 104 means: Connection reset by peer
The Server closed the Connection.
Please double check the server.
Maybe some timeout. ...

Unrelated to dav client. Closing

**Comment by vaajnur** [comment]
thank you for answer, but server is checked. it's not work among 2 weeks. But small files are transmitted.

**Comment by staabm** [comment]
>2GB sounds like 32 bit limitations

**Comment by vaajnur** [comment]
it's Yandex Disk problem, i tried to upload with pure curl from console - very long.
