### ISSUE TITLE
How to move a file ?

### ISSUE THREAD

**Issue by vipera7** [sabre-io/dav#1215]
I want to move a file in Nextcloud using WebDAV.

```
<?php
include '../../3rdparty/dav/vendor/autoload.php';
use Sabre\DAV\Client;
$client = new Client(array('baseUri' => $hostname, 'userName' => $username, 'password' => $password));
$response = $client->request('MOVE', $url."somefile", $url."folder/somefile");
```

The following doesn't move my file into the folder

**Comment by DeepDiver1975** [comment]
what does $url look like?
what is the response from the server?

^this should give enough pointers on whats going wrong

**Comment by vipera7** [comment]
`$url` is `/files/remote.php/webdav/`

Error :

`array(3) { ["body"]=> string(233) " Sabre\DAV\Exception\BadRequest The destination header was not supplied " ["statusCode"]=> int(400) ["headers"]=> array(19) { ["date"]=> array(1) { [0]=> string(29) "Tue, 17 Dec 2019 10:10:42 GMT" } ["server"]=> array(1) { [0]=> string(22) "Apache/2.2.15 (CentOS)" } ["strict-transport-security"]=> array(1) { [0]=> string(44) "max-age=15768000; includeSubDomains; preload" } ["x-powered-by"]=> array(1) { [0]=> string(10) "PHP/7.1.33" } ["set-cookie"]=> array(6) { [0]=> string(76) "ocyvic5tf=807e07e2d83e86; path=/files; secure; HttpOnly" [1]=> string(182) "oc_sessionPassphrase=kvmpVRZjT3ImQ3qWzI7ylUaOsUbIiQxau6b7f1fwckXJJM8SKg4; path=/files; secure; HttpOnly" [2]=> string(108) "nc_sameSiteCookielax=true; path=/files; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax" [3]=> string(114) "nc_sameSiteCookiestrict=true; path=/files; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict" [4]=> string(76) "ocyvic3wn5tf=f9439e7523cb; path=/files; secure; HttpOnly" [5]=> string(69) "cookie_test=test; expires=Tue, 17-Dec-2019 11:10:42 GMT; Max-Age=3600" } ["expires"]=> array(1) { [0]=> string(29) "Thu, 19 Nov 1981 08:52:00 GMT" } ["cache-control"]=> array(1) { [0]=> string(35) "no-store, no-cache, must-revalidate" } ["pragma"]=> array(1) { [0]=> string(8) "no-cache" } ["content-security-policy"]=> array(1) { [0]=> string(19) "default-src 'none';" } ["referrer-policy"]=> array(1) { [0]=> string(11) "no-referrer" } ["x-content-type-options"]=> array(1) { [0]=> string(7) "nosniff" } ["x-download-options"]=> array(1) { [0]=> string(6) "noopen" } ["x-frame-options"]=> array(1) { [0]=> string(10) "SAMEORIGIN" } ["x-permitted-cross-domain-policies"]=> array(1) { [0]=> string(4) "none" } ["x-robots-tag"]=> array(1) { [0]=> string(4) "none" } ["x-xss-protection"]=> array(1) { [0]=> string(13) "1; mode=block" } ["content-length"]=> array(1) { [0]=> string(3) "233" } ["connection"]=> array(1) { [0]=> string(5) "close" } ["content-type"]=> array(1) { [0]=> string(30) "application/xml; charset=utf-8" } } }`

**Comment by DeepDiver1975** [comment]
> The destination header was not supplied

Please read up how move works: https://tools.ietf.org/html/rfc4918#section-9.9

**Comment by vipera7** [comment]
Can you give an example on how to use it ?
