### ISSUE TITLE
[FreeBusyGenerator] Don't care participant status when caculate freebusy 

### ISSUE THREAD

**Issue by tuanlc** [sabre-io/dav#1216]
Hello,
I'm working on FreeBusy feature and encountering an issue.

**Behavior:**
As user A, I invite user B to an event at time range T
As user B, I decline the event
As user C, I invite user B to another event with the same time range T
User C see user B is unavailable

**Expect Behavior:**
User C see user B is available

I debugged and see that the freebusy calculator does not care participant status of the target attendee.

Could you please take a look and tell me if I'm wrong or is it expected behavior or a bug?
Thanks in advance!

**Comment by staabm** [comment]
@evert @DeepDiver1975 can anyone of you give feedback on this question?

**Comment by evert** [comment]
My knowledge of this is fading, it's been a while.

I _believe_ that when an attendee declines an event, calendar applications typically:

1. Remove the event
2. In the case of a recurring event, add an exception to that event in the same calendar.

However, if the declined event/instance is not removed, I believe that the calendar client should set the `TRANSP` property for that event/instance to 'TRANSPARENT', which is the main mechanism freebusy filters out irrelevant events.

However, I am not really 100% sure of this. I couldn't find a source for this when doing a brief look. I would be curious to see how calendar clients behave when events are declined and *not* deleted. Do they change `TRANSP` ?

**Comment by tuanlc** [comment]
Hello @evert , @staabm 
Thank you for the quick answer.

> Do they change TRANSP ?

No, they don't. But now, I understand the business. [transp code](https://github.com/sabre-io/dav/blob/master/lib/CalDAV/Xml/Property/ScheduleCalendarTransp.php#L21)
Thank you so much again for the nice information.
