### ISSUE TITLE
Release 4.0.3

### ISSUE THREAD

**Issue by phil-davis** [sabre-io/dav#1221]
PR #1181 was merged, and other things have been merged in the last few months.

Do a release?

@staabm @DeepDiver1975

**Comment by staabm** [comment]
Jep. Will try it next week. @DeepDiver1975 feel free to do it earlier in case you have some spare minutes

**Comment by DeepDiver1975** [comment]
released

**Comment by staabm** [comment]
@phil-davis could you add and maintain the owncloud integration tests with sabre/dav as a separate build job in our sabre/dav repo?

That could help both projects to increase stability
