### ISSUE TITLE
Can we have full single-file example of per-user directory?

### ISSUE THREAD

**Issue by MPNull** [sabre-io/dav#1235]
http://sabre.io/dav/per-user-directories/

The tutorial contains syntax errors which makes it much harder to understand when there's a nub like me trying to figure it out.

**Comment by PHPGangsta** [comment]
Could you be a bit more verbose, and tell us, where the syntax errors are?

The source code of that website is here:
https://github.com/sabre-io/sabre.io/blob/master/source/dav/per-user-directories.md

Would be perfect if you could fix it, and send a Pull Request.
