### ISSUE TITLE
Is there difference between Web and Mapped Drive Transfer?

### ISSUE THREAD

**Issue by MPNull** [sabre-io/dav#1243]
I have successfully implemented a quota-watcher which checks quota when uploading. It works perfectly with Web Plugin. It will throw: new InsufficientStorage(); if the available quota is less than the file size that is uploaded.

There's literally zero errors when using Sabre on Web, but if I use Mapped Drive, Mobile Client, or something else, it will ignore that error and still uploads the file. How should I interrupt the transfer?

What's the difference between Web and Client?

Thanks.

**Comment by DeepDiver1975** [comment]
Without seeing any code it is hard to tell whats going on.

Maybe you attached the quota watcher only to the web plugin (I assume you mean the browser plugin) ...

Anyway - without code there is little help.

**Comment by DeepDiver1975** [comment]
Finally - it is open source - attach a debugger and walk through the code and you will find out why ... ;-)

**Comment by MPNull** [comment]
https://pastebin.com/kuAc5Tfz

That's executed on each upload (UserDirectory) extended with Directory and implemented IQuota and IDirectory. **I have verified that.** If I kill it with die("FooBar"); it shows FooBar, and it interrupts transfer for Browser and rest of the clients successfully, but for an unknown reason only Browser Plugin is able to handle my condition. If the Browser is working I don't find a reason why clients don't.

Server: https://pastebin.com/E0dyrDi7

**Comment by MPNull** [comment]
I want also remind that quotaLeft and fsize is defined and prints out correct amount of bytes (verified) and logically if it wouldn't, it won't work even on the browser.

**Comment by DeepDiver1975** [comment]
You might want to look into this QuotaPlugin to get some ideas: https://github.com/owncloud/core/blob/2074883c3f66e9aa7d70e7522719a637c3161053/apps/dav/lib/Connector/Sabre/QuotaPlugin.php#L130

Just a hint .... good luck
