### ISSUE TITLE
Reccuring events

### ISSUE THREAD

**Issue by iammatis** [sabre-io/dav#1253]
I'm using the Mongo adapter for SabreDav.

I have following event:
```
BEGIN:VCALENDAR
...
BEGIN:VEVENT
UID:e03cfe76-851e-42f9-a05f-9135301ca765
DTSTART:20200106T070500Z
DESCRIPTION:Branch opening hours for Monday
SUMMARY:Monday
RRULE:FREQ=WEEKLY;INTERVAL=1
DTEND:20200106T110000Z
CATEGORIES:OPENING HOURS
DTSTAMP:20200221T180947Z
END:VEVENT
END:VCALENDAR
```

An event that should recur every week forever. And i make following `REPORT`:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<C:calendar-query
	xmlns:C="urn:ietf:params:xml:ns:caldav">
	<D:prop
		xmlns:D="DAV:">
		<D:getetag/>
		<C:calendar-data/>
	</D:prop>
	<C:filter>
		<C:comp-filter name="VCALENDAR">
			<C:comp-filter name="VEVENT">
				<C:time-range start="20200113T060500Z" end="20200113T140000Z" />
			</C:comp-filter>
		</C:comp-filter>
	</C:filter>
</C:calendar-query>
```

Basically for the next week around the same time, but I don't get any objects back.

**Comment by DeepDiver1975** [comment]
Does this work for another backend?
If so: this is an issue which needs to be debugged in the mongo backend

**Comment by iammatis** [comment]
Unexplainably it started working. Both I and colleague were looking at it and it wasn't working and all of a sudden day after it started. I didn't change anything regarding the sabre settings so we have no idea what happened.
