### ISSUE TITLE
installation issue 

### ISSUE THREAD

**Issue by Unitedpotteries** [sabre-io/dav#1256]
Hi everyone, 

Could some one please help me to check virtual host below? 
I had being stuck when I installed the Sabre dav on Centos 7. After I used composer to get the sabre/dav to server, I created conf file in /etc/httpd/vhost.d/ and /var/www/html/katana/ to setup virtual host. However I can't access to the web page of Sabre on server to config the system. 
Is there any new virtual configuration for Sabre/dav? or do we have any other way to set up the web page for Sabre/dav without virtual host?
I'm using php 7.3 and apache at this time, and this is my virtual host config:
<VirtualHost *:443> *: is local IP address

    DocumentRoot /var/www/katana/html
    ServerName dav.example.org

    RewriteEngine on
    # Generally already set by global Apache configuration
    # RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteRule /.well-known/carddav /dav.php [R=308,L]
    RewriteRule /.well-known/caldav  /dav.php [R=308,L]

    <Directory "/var/www/katana/html">
        Options None
        # If you install cloning git repository, you may need the following
        # Options +FollowSymlinks
        AllowOverride None
        # Configuration for apache-2.4:
        Require all granted
        # Configuration for apache-2.2:
        # Order allow,deny
        # Allow from all
    </Directory>

    <IfModule mod_expires.c>
        ExpiresActive Off
    </IfModule>

</VirtualHost>

Thanks :)

**Comment by DeepDiver1975** [comment]
Katana is no longer maintained. Afaik it cannot run on php7.x
Please give Baikal a try. Thx
