### ISSUE TITLE
Calling PUT on CalDav returns 404 with incorrect calendar folder within the error message

### ISSUE THREAD

**Issue by mindisk** [sabre-io/dav#1258]
Greetings, 

I am using SabreDAV to manage various calendar events of my organization.  When inserting some events, I am experiencing a bizarre issue where I get a error message indicating that a calendar does not exist.

Process flow:
- Create calendar.
- Insert calendar event into the folder.
- Returns error. 

Request:
```
Method: PUT, 
RequestUri: 'test@email.com/AAMkADFjMjk2ZDc1LTJjZjYtNDZjYS05YzYwLTNkZDQ4N2I0N2ZkYwBGAAAAAADqGH1n8tY1R7tlZ9uBCeQ0BwAGB3c4bPyBSqPyoptM4jf9A7ygWZMzAAAMhqE6kq0yTbLCWf5htGtXAACiA3y5AAA%3d/AAMkADFjMjk2ZDc1LTJjZjYtNDZjYS05YzYwLTNkZDQ4N2I0N2ZkYwFRAAgI17-O_4JAAEYAAAAA6hh9Z-LWNUe7ZWfbgQnkNAcABgd3OGz8gUqj8qKbTOI3-QO8oFl6JQAADIahOpKtMk2ywln_YbRrVwAAogOMmQAAEA%3d%3d.ics', 
Version: 1.1, 
Content: System.Net.Http.StringContent,
Headers:{  Content-Type: text/calendar; charset=utf-8 } 
Content: 
BEGIN:
VCALENDAR
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 4.0//EN
VERSION:2.0
BEGIN:VEVENT
ATTENDEE;CN=Test;RSVP=TRUE:MAILTO:test@email.com
CREATED:20200219T080906Z
DTEND:20200304T080000Z
DTSTAMP:20200303T124521Z
DTSTART:20200304T070000Z
LAST-MODIFIED:20200303T005201Z
LOCATION: Office
ORGANIZER;CN=Test:MAILTO:test@email.com
SEQUENCE:0
SUMMARY:Test event
UID:AAMkADFjMjk2ZDc1LTJjZjYtNDZjYS05YzYwLTNkZDQ4N2I0N2ZkYwFRAAgI17-O_4JAAEYAAAAA6hh9Z-LWNUe7ZWfbgQnkNAcABgd3OGz8gUqj8qKbTOI3-QO8oFl6JQAADIahOpKtMk2ywln_YbRrVwAAogOMmQAAEA==
END:VEVENT
END:VCALENDAR
```

Response:
```
StatusCode: 404, 
ReasonPhrase: 'Not Found', 
Version: 1.1, 
Content: System.Net.Http.HttpConnectionResponseContent, 
Headers:
{
  Date: Tue, 03 Mar 2020 12:46:09 GMT
  Server: Apache/2.4.29
  Server: (Ubuntu)
  X-Powered-By: PHP/7.2.24-0ubuntu0.18.04.3
  X-Sabre-Version: 4.0.3
  Content-Length: 439
  Content-Type: application/xml; charset=utf-8
} 
Content: 
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>4.0.3</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Node with name 'AAMkAGFkMzIyYTA5LWI4NzYtNGQ0OC1hZGQ5LTczZTNkMjhkNDgxZQBGAAAAAADTmNEbbY02QpY0Uc5R6OSABwAfw9cv_l1TQo89u1mNA-nQAAAAAAEHAABiTOrrOHdVSqbuXspuRrveAAFprZoWAAA%3d' could not be found</s:message>
</d:error>
```

The issue here is that the response returns 404 indicating that the calendar node is not found. However, the response payload that contains error message about calendar not existing, contains different calendar than it was in request URL. 

The original request tried to insert an event into calendar:
```
AAMkADFjMjk2ZDc1LTJjZjYtNDZjYS05YzYwLTNkZDQ4N2I0N2ZkYwBGAAAAAADqGH1n8tY1R7tlZ9uBCeQ0BwAGB3c4bPyBSqPyoptM4jf9A7ygWZMzAAAMhqE6kq0yTbLCWf5htGtXAACiA3y5AAA%3d
```
While the SabreDav returned error for calendar:
```
AAMkAGFkMzIyYTA5LWI4NzYtNGQ0OC1hZGQ5LTczZTNkMjhkNDgxZQBGAAAAAADTmNEbbY02QpY0Uc5R6OSABwAfw9cv_l1TQo89u1mNA-nQAAAAAAEHAABiTOrrOHdVSqbuXspuRrveAAFprZoWAAA%3d
```

As you can see, it is a mismatch between the targeted calendar and the response payload.

Setup information:
Host: Ubuntu:18.04
PHP: 7.2
SabreDAV version: 4.0.3

I had to make some changes in order to run SabreDAV against MSSQL. 
The changes include using MSSQL connection driver for PHP and minor change in bin/CalDAV/Backend/PDO.php to:
```
Line 255:  $calendarId = $this->pdo->lastInsertId();
Line 274:  $this->pdo->lastInsertId(),
```

I want to believe that these changes should not cause this issue since most of the calendar events are correctly inserted. Could it?

Have you ever seen this before? If yes, do you know the cause of it?

Thanks!

**Comment by DeepDiver1975** [comment]
To rule out that MSSQL and/or your changes are causing this issue I suggest to test this all with the MySQL backend. If the issue still exists we can look deeper. THX

**Comment by mindisk** [comment]
I see. I will try it out. I will let you know about the findings.

**Comment by mindisk** [comment]
Hi, 

Sorry for taking so long to test using MySQL database engine. 

I ran SabreDav (v4.1.0) against MySQL v8.0.19 (Community Server) database engine and I can verify that same issue still persist. 

Now, I believe I forgot to mention that I see this issue occurring while I am attempting to push several hundred events (spanning over multiple users) concurrently to SabreDav from external system like Microsoft Exchange and Google. 

Can this be a concurrency issue within SabreDav?
My other guess would be that there is a encoding/decoding issue within the SabreDav.

I will attempt to run push all calendar events sequentially to observe the behavior of SabreDav. 

Nonetheless, I would appreciate any additional information and/or tips you can provide to solve this issue.

**Comment by mindisk** [comment]
I have testing pushing calendar events sequentially and can confirm, that the issue still persist. 
At this point I am out of options and ideas what can cause this issue. 
I will wait for your response to see what would be the next steps in solving this issue.

**Comment by mindisk** [comment]
Since then I have decided to move away from using SabreDav. 
No further update on the case.
