### ISSUE TITLE
Notes not working

### ISSUE THREAD

**Issue by tiiiecherle** [sabre-io/dav#1262]
Hey,

first of all thanks for all the great work put into this. I am a long-term baikal and now davis user.

As asked [here](https://github.com/tchapi/davis/issues/4) We would like to use the notes feature. 

I added a calendar (with only notes instance functionality to a new user) but when adding the caldav account to iOS or macOS (both latest up-to-date versions) the connection to the server and the account works, but it only presents calendar and contacts as available options, not notes. Is there anything that has to be activated or changed to use this?

Thanks for looking into it and for the help in advance

Kind regards

**Comment by evert** [comment]
Unfortunately, I don't think there is a standard implementation of notes that Apple software supports. It's a default option when you connect to Exchange servers. CalDAV does have something called `VJOURNAL` which is kinda close, but Apple doesn't support this.

If they do support a DAV version of 'notes', it's either a proprietary extension or I'm not aware of an open specification.

**Comment by devvv4ever** [comment]
Just a small addition regarding Notes via CalDAV. 

DAVx5 can now synchronize VJOURNAL on Android, and we've developed a Journal/Notes/Tasks app in collaboration with https://jtx.techbee.at/ called jtx Board -so that this can be used now :) Maybe you want to give it a try if you have an Android device somewhere.

**Comment by tiiiecherle** [comment]
@devvv4ever Thanks for the hint and the link. We mostly use apple devices that sync with the [davis project](https://github.com/tchapi/davis) which is installed on our own linux server.
Would be nice to see a future feature regarding notes for it.
