### ISSUE TITLE
Clusterized nodes

### ISSUE THREAD

**Issue by peter-mogensen** [sabre-io/dav#1272]
Hi,

I hate to ask a question here, but the shutdown notice on the maillinglist suggested to ask on Github.

I was wondering if SabreDAV was designed for running several stateless nodes against the same database? It doesn't seem it's using transactions in it's SQL usage against PostgreSQL and I can see a least some statements where the lack of transactions have temporary inconsistent state. (like the update of sync-token after a change) ... but in that case there might be some reasoning about such an update only needs to be eventually consistent.

Can you run SabreDAV nodes stateless in parallel against the same database having HTTP request randomly distributed among them?

**Comment by evert** [comment]
sabre/dav will not do any session-related or local thing out of the box, so if you use stock sabre/dav this should 100% work.
