### ISSUE TITLE
Please allow PROPPATCH'ing the getlastmodified property of a file

### ISSUE THREAD

**Issue by mgutt** [sabre-io/dav#1277]
At the moment its impossible to update the getlastmodified timestamp of a file. [Sabre DAV returns an 403 Forbidden error](https://github.com/owncloud/core/issues/33502). I know that getlastmodified has been protected as this is stated in the spec, but [the spec says "should" and not "must"](https://tools.ietf.org/html/rfc4918#section-15.7):

> Protected:   SHOULD be protected because some clients may rely on the
>       value for appropriate caching behavior, or on the value of the
>       Last-Modified header to which this property is linked.

Protecting it to avoid re-filling a cache makes it impossible for all clients to correct/preserve the file modification time. Because of that Nextcloud/Owncloud use the special `X-OC-MTime` header as a dirty hack, but [it works only for file uploads](https://github.com/nextcloud/server/issues/21536) (`PUT`).

**Comment by DeepDiver1975** [comment]
One can simply remove the property from this public array which holds all protected props: https://github.com/sabre-io/dav/blob/30e42f408516512ea44e0ca63b2843c924ad2946/lib/DAV/Server.php#L108

**Comment by mgutt** [comment]
> One can simply remove the property from this public array which holds all protected props:
> 
> https://github.com/sabre-io/dav/blob/30e42f408516512ea44e0ca63b2843c924ad2946/lib/DAV/Server.php#L108

Please remove it by default, because no provider will do that. Of course it will be overwritten on every update, too.

**Comment by DeepDiver1975** [comment]
>  Of course it will be overwritten on every update, too.

not really - you can manipulate the array of the sabre server instance within your own codebase ...
```
$server = new Dav\Server(..);
$server->protectedProperties = array_diff($server->protectedProperties, ['{DAV:}getlastmodified']);

**Comment by mgutt** [comment]
> you can manipulate the array of the sabre server instance within your own codebase ...
> 
> ```
> $server = new Dav\Server(..);
> $server->protectedProperties = array_diff($server->protectedProperties, ['{DAV:}getlastmodified']);
> ```

Ok, good to know, but as I said. Nearly no provider will do that, as nearly nobody asks for it, as nearly nobody knows the reason.

I mean, why added Owncloud the X-OC-MTime variable? And why is Webdrive.com adding custom Dav properties? They all did that because this tiny property is locked. If you search for "webdav preserve timestamp" it will return thousands of issues and discussions. And there are only a handful that tried PROPPATCH as they did as much research as I did (and they failed).

And ask yourself: Will Owncloud, Nexcloud or rclone change their code and add PROPPATCH'ing the timestamp if one tiny provider or a private person changes his installation? And this exactly my final approach. I like to have rclone sync all my files and preserve the dates even after I moved to another cloud provider or copied the files, which all kills the modification times. Reuploading everything wastes time, energy and ressources. Not really friendly for the environment and I bet most people solve it by doing this (I need to reupload 30TB because my old NAS did not support X-OC-MTime).

And if Sabre/Dav changes this behaviour, there is a good chance that other WebDAV server softwares will change it, too.

**Comment by DeepDiver1975** [comment]
> And if Sabre/Dav changes this behaviour, there is a good chance that other WebDAV server softwares will change it, too.

I doubt that sabre/dav has any influence at all to any providers. In all the project history nobody except a few vendors contributed to this project. I assume they all maintain their own private forks.

Anyway - I honestly don't care much if we change this or not. In any case the impact needs to be analysed. 
From the owncloud perspective I can say that we most likely will not adapt this change because the last modified datetime of a file is an integral part of the sync protocol. It is maintained by the server and clients have no control of it by intention - exception is the upload to allow properly initialize it when a file is newly uploaded.

But we are drifting of here ..... happy to discuss this in https:/github.com/owncloud/core ...

**Comment by mgutt** [comment]
> It is maintained by the server and clients have no control of it by intention - exception is the upload to allow properly initialize it when a file is newly uploaded.

This is a contradiction as there does not exist an exception. Adding the X-OC-MTime variable was a hack by Owncloud to bypass Sabre/dav's decision to make this property protected. This works only in the Owncloud world and not on other software using Sabre/Dav.

And why should only the server control the timestamp? There is no other network file system/protocol doing this (SMB, FTP, NFS, ...). And who decides that it is ok to change the modification time on upload and not through MOVE, COPY, etc? For me it sounds like arbitrariness.

**Comment by DeepDiver1975** [comment]
> This is a contradiction as there does not exist an exception. Adding the X-OC-MTime variable was a hack by Owncloud to bypass Sabre/dav's decision to make this property protected. This works only in the Owncloud world and not on other software using Sabre/Dav.
> 
> And why should only the server control the timestamp? There is no other network file system/protocol doing this (SMB, FTP, NFS, ...). And who decides that it is ok to change the modification time on upload and not through MOVE, COPY, etc? For me it sounds like arbitrariness.

Discussions about design decision in owncloud do not belong here. As said above - you are welcome to discuss this in the scope of the owncloud repos.

From an sabre/dav prespective there is a way to allow changing getlastmodified - case closed in here from my pov.

**Comment by mgutt** [comment]
> Discussions about design decision in owncloud do not belong here

I'm not talking about the design decision in Owncloud. I'm talking about a design decision in Sabre/Dav. I'm not even using Owncloud. You said there is an exception that "properly initialize it when a file is newly uploaded". "It" is the "getlastmodified" property and ONLY Sabre/Dav is controling it and does NOT have an exception for uploads. I only gave an example which WebDAV software add one to bypass this limitation and now you are using this example as an argument to stop this issue?!

I can give an other example: Webdav.com tried to solve this issue by adding custom dav properties:
https://support.southrivertech.com/support/solutions/articles/9000144573-webdav-server-timestamps

This means different WebDAV clients aren't compatible to each other and of course all files loose their timestamps if you move to an other provider. And this while we are talking about an open standard.

The spec says "SHOULD" and by [RFC2119](https://www.ietf.org/rfc/rfc2119.txt) it is allowed to ignore it. And finally you miss to give a valid reason why it must be protected.  You said "the impact needs to be analysed". Who does it?

**Comment by staabm** [comment]
@evert any opinion on this topic?

**Comment by evert** [comment]
This property controls the Last-Modified http headers. Allowing a client to change this will break everything related to the If-Modified-Since and If-Unmodified-Since precondition headers. Users can get stale versions of files because they *think* they have latest server state, while in fact they only have a state from the server with the highest last modification date they have seen.

I understand that this is a pain, but this is not fixable. The way to handle this is with a new property that describes the last modification date as metadata of the file, but not the last time when the server truly returned a new state.

**Comment by mgutt** [comment]
@evert 
You are describing a situation that is a problem if userA shares a file with userB, userB downloads it and then wents offline and finally userA changes the file content and resets the timestamp to the old one. This leaves some questions: Why should a user change the timestamp while he is sharing recent changed files? And why is it needed to forbid that? I mean, do we forbid deleting files because a user could delete files by accident?

But back to the situation.  This means userB has an older version of the file and does not download the newer version, because timestamps didn't change. Correct? Wrong. The clients do not persist on last-modified for syncing. They use the etag, because getetag is a MUST:
"The getetag property MUST be defined on any DAV-compliant resource that returns the Etag header."

And its a MUST to use them:
"Note that since [RFC2616] requires clients to use ETags where provided, a server implementing ETags can count on clients using a much better mechanism than modification dates for offline synchronization or cache control."

The spec describes in many sections why ETags are necessary like for locking files:
"A client might fail to renew a lock, for example, when the lock times out and the client is accidentally offline or in the middle of a long upload.  When a client fails to renew the lock, it's quite possible the resource can still be relocked and the user can go on editing, as long as no changes were made in the meantime.  ETags are required for the client to be able to distinguish this case."

And the [CalDAV spec](https://tools.ietf.org/html/rfc4791) is even clearer in its definition:
"A response to a GET request targeted at a calendar object resource MUST contain an ETag response header field indicating the current value of the strong entity tag of the calendar object resource."

And it is not allowed by spec to reuse an etag if the content changes:
"For any given URL, an "ETag" value MUST NOT be reused for different representations returned by GET."

This means even if the last-modified timestamp has been changed, userB's client will download the newer version of the file as his client relies on the changed etag and not an the timestamp. This simply means If-Modified-Since and If-Unmodified-Since headers are not recommend and as far as I know not used by WebDAV clients.

And by the way: Your example does not cover PUT, MOVE and COPY. Its only for GET.

Funnily the spec does not mention "PUT" and live properties. Even the Overwrite behavior isn't mentioned (the overwrite header is only described for COPY and MOVE).

But its clear for COPY (live properties = timestamps):
"When the destination is an unmapped URL, a COPY operation creates a new resource much like a PUT operation does.  Live properties that are related to resource creation (such as DAV:creationdate) should have their values set accordingly."

and for MOVE:
"Note that some server implementations use the file system date modified value for the DAV:getlastmodified value, and this can be preserved in a MOVE"
and
"MOVE is frequently used by clients to rename a file without changing its parent collection, so it's not appropriate to reset all live properties that are set at resource creation.  For example, the DAV: creationdate property value SHOULD remain the same after a MOVE."

Side note: At least a "MOVE" SHOULD preserve the getlastmodified timestamp.

**Comment by evert** [comment]
It's quite simple: If I do a GET request twice, and the response has changed the second time, the second GET request must have a later Last-Modified header (if there was one). We can't guarantee this if users can change the value.

Even if we could reliably assume that 0 clients always prefer ETags (they don't), it would still not be correct behavior.

**Comment by mgutt** [comment]
> It's quite simple: If I do a GET request twice, and the response has changed the second time, the second GET request must have a later Last-Modified header (if there was one). We can't guarantee this if users can change the value.

Yes, this part in spec describes it:
>For any given URL, the "Last-Modified" value MUST increment every
      time the representation returned upon GET changes (within the
      limits of timestamp resolution)."

But what if the date was never correct? The problem started here:
>The last-modified date on a resource SHOULD only
      reflect changes in the body (the GET responses) of the resource.
      A change in a property only SHOULD NOT cause the last-modified
      date to change, because clients MAY rely on the last-modified date
      to know when to overwrite the existing body.

The client uses PUT to transmit the resource and although the last-modified date SHOULD not change, it did, as Sabre/Dav does not allow to set the last-modified date. Now we have our resource on our server with an different date compared to the client. The only solution is now, to download all files and using the tools (checksum, touch) of the client to change the local date and this is finally against [the meaning of the Last-Modified date as described in RFC7232](https://tools.ietf.org/html/rfc7232#section-2.2):
>since its use in conditional requests
   and evaluating cache freshness ([RFC7234]) results in a substantial
   reduction of HTTP traffic on the Internet and can be a significant
   factor in improving service scalability and reliability.

So why does Sabre/Dav not allow to set the last-modified date on PUT although the specs says, that it SHOULD NOT be changed as long the content did not change?

P.S. If there are really clients out there relying on the last-modified date, it would be impossible to sync multiple WebDAV servers.

**Comment by evert** [comment]
The `Last-Modified` header should reflect the last time when a response to `GET` changed. It's true that allowing this to be set just with `PUT` could create a valid state from a HTTP perspective, but only if a resource with that uri never existed in the past. This is not easy to guarantee, especially given that some clients will actually `DELETE` and follow-up with `PUT`.

Regardless, and this is my last word on this... this is about intent. The intent of the header is to reflect the last time a response to `GET` changed. It's not for user-focused meta-data that indicates the last time somebody, somewhere hit a 'save' button that caused a logical change.

For meta-data like this, a different property should be used. There's probably a few different ones out there, like `X-OC-MTime`, but others too. I think if sabredav vets one of those alternative properties as a 'good default', and maybe provides mappings to some of the other properties that are out there, like microsoft's, I think that's a better path than to try to alter the semantics of core HTTP concept.

I'm locking this thread now, as I think everything about this that could be said, has been said. Perhaps you still disagree, and that's OK, but I don't think we'll be able to find a middle ground here.
