### ISSUE TITLE
Why isn't sabredav using the mime_content_type() php function?

### ISSUE THREAD

**Issue by AvverbioPronome** [sabre-io/dav#1286]
https://github.com/sabre-io/dav/blob/5736f943c90d8d73d04cd8944d8c913811dc7360/lib/DAV/FS/File.php#L83

https://www.php.net/manual/en/function.mime-content-type.php

**Comment by DeepDiver1975** [comment]
PR welcome - THX

**Comment by AvverbioPronome** [comment]
I have a first iteration, I run the unit tests and I get 

```
Tests: 1605, Assertions: 1978, Errors: 306, Skipped: 219.
```

Is this expected?

Also: is there a dockerized test environment I can run?

**Comment by DeepDiver1975** [comment]
Please submit the pr and we can have a look together

**Comment by evert** [comment]
See discussion in #1287
