### ISSUE TITLE
Cannot edit file directly through webdav.

### ISSUE THREAD

**Issue by tedchou12** [sabre-io/dav#1294]
I am trying to open a word doc or txt file directly via webdav and edit and save.
There is no problem opening and writing to webdav, but when clicking save.
Word creates a lot of `file-name.docx.sb-17bc70f8-eb58yw` folders with `~WORD` files.
And the original `file-name.docx` becomes 0 byes.
Since I am actually writing to AWS S3, there is an error:
```
func_upload()
exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "PutObject" on "https://my-domain-s3bucket.s3.us-east-2.amazonaws.com/folder/file-name"; AWS HTTP error: Server error: `PUT https://my-domain-s3bucket.s3.us-east-2.amazonaws.com/folder/file-name` resulted in a `501 Not Implemented` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NotImplemented</Code><Message>A header you provided implies function (truncated...)
 NotImplemented (server): A header you provided implies functionality that is not implemented - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><Header>Transfer-Encoding</Header><RequestId>01435B826C991BBF</RequestId><HostId>kpaBs1/UC82ZY5FaXwGD/OMy24V3SjPEDlNzj2Hc6wvqAjS1Jal7e4Mr8rog+BsW4Ps0fMlyeE8=</HostId></Error>'
```
I have already defined the lock file, but seems like I can't get it to work.

EDIT
I am guessing that since the file_stream writes too slowly to the S3, so when the file stream is finally written to S3, the file is deleted on webdav. I was thinking is there a possibility to force editing or saving temporary files on users local client and when the click on save, to save it to S3?

Thank you.

**Comment by DeepDiver1975** [comment]
Not really a sabre/dav issue - right?

I assume you are implementing the write operation and use the aws sdk to save the file.
from my understanding it is upon you to use the proper aws apis ...

Or am I missing anything?

**Comment by tedchou12** [comment]
You are right.
Yes. I am trying to implement the write operations to connect with aws s3. I will address this to aws.
The actual error is this one:
```
InvalidArgumentException: Found 1 error while validating the input provided for the PutObject operation:
[Metadata][Content-Type] must be a string or an object that implements __toString(). Found bool(false) 
```
Seems like the resource is quite limited. May be nobody is doing this at all.

Thanks.

Ted.
