### ISSUE TITLE
dav

### ISSUE THREAD

**Issue by Fraquane** [sabre-io/dav#1302]
﻿Hello ,

i was finally able to install roundcube irony & kolab but i have a big problem that i can't solve ..

I have been asked to find out who I am and the password to access the web page

except that not knowing the identifiers how can we deactivate this authentication protection

we absolutely need help could you help us via PC control
![unnamed](https://user-images.githubusercontent.com/73375074/97611578-a84aa900-1a16-11eb-991b-a372fcad0084.jpg)
![unnamed1](https://user-images.githubusercontent.com/73375074/97611585-a97bd600-1a16-11eb-80f1-a5c349b68684.jpg)

here is our e-mail:

orlando@fl.fr

or on discord: Fraquane # 2219

see Attachment
thank you for your feedback

**Comment by ByteHamster** [comment]
This does not sound like it is related to the sabre/dav server library. Please contact the developers of the software you are trying to install.
