### ISSUE TITLE
Authentication error No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured

### ISSUE THREAD

**Issue by rheman** [sabre-io/dav#1336]
Hello everyone,

@DeepDiver1975 

This is my first experience on SabreDav.
I am using version 4.1.5 under Apache/2.4.29 (Ubuntu) with mod_php. I am running php 7.3
 
So I follow this tutorial to setup the server. [https://sabre.io/dav/gettingstarted/](https://sabre.io/dav/gettingstarted/)  [https://sabre.io/dav/webservers/](https://sabre.io/dav/webservers/)  and the server is working because after testing I got the attached screenshot.

I tried to add a simple authentication using BasicCallBack this way.

$authBackend = new Sabre\DAV\Auth\Backend\BasicCallBack(function($username, $password) {
	return true;
});
$authPlugin = new Sabre\DAV\Auth\Plugin($authBackend);
$server->addPlugin($authPlugin);

But after adding authentication I got the following error and I really don't know how to overcome.

**No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured**

I need you guidance.

regards,

**Error I got after authentication enabled.**

![Screenshot from 2021-03-23 17-38-42](https://user-images.githubusercontent.com/4598772/112192277-bcc65280-8bfe-11eb-94d7-3e916de96dd2.png)

**Screenshot I got after testing without authentication enabled**

![Screenshot from 2021-03-23 17-34-14](https://user-images.githubusercontent.com/4598772/112191671-2560ff80-8bfe-11eb-9fea-04c916b23962.png)

**Comment by johnfuller** [comment]
If you're using Apache, then you might need to add this to your rewrite rules (for example, within a .htaccess file.)

`
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
`
