### ISSUE TITLE
Question of understanding

### ISSUE THREAD

**Issue by Ghost108** [sabre-io/dav#1339]
Good morning !

I have a own calDAV Server (Synology Contacts) on my Synology NAS.
Is this package (sabre dav) a php library, which allows me to do the following tasks?:

- connect to my caldav server
- get / create / delete / modify events

If yes:
Is there a simple php basic code available for all this task?
Thank you very much !

**Comment by DeepDiver1975** [comment]
sabre is a server side library - you can implement your own caldav/carddav/webdav server with it.

While it also has a client with basic functionalities I'd say sabre is not the tool for your task.

**Comment by Ghost108** [comment]
okay thanks !
can you show me a tool for my tasks ?
