### ISSUE TITLE
Upload filestream to webdav server

### ISSUE THREAD

**Issue by totumfaktum88** [sabre-io/dav#1353]
Hello there,

i need a little help about file uploads with your package, cause i didn't find any answers (stackoverflow etc.) about that.

So here is the situation:

I develop a laravel project. I would like to use nextcloud to store large files. I found the [league/flysystem-webdav](https://packagist.org/packages/league/flysystem-webdav) package that use your package.

Unfortunately some another package [spatie-laravel-media-library](https://packagist.org/packages/spatie/laravel-medialibrary) use filestream when it try to save it to a path.

Unfortunately in this circumstances the client will throw an exception with this message (only with filestream request):

curl_errno: 65, curl_errmsg: necessary data rewind wasn't possible

Example:

```
<?php

use Sabre\DAV\Client;
$client = new Client($config);

$file = fopen($path, 'r');
$client->request("PUT", $pathPrefix, $file);

if( is_resource($file) ){
    fclose($file);
}
```

Response:

```
array:3 [
  "status" => 1
  "curl_errno" => 65
  "curl_errmsg" => "necessary data rewind wasn't possible"
]
```

There is any config option that can help me out?

Thanks for your help!

**Comment by totumfaktum88** [comment]
Unfortunately same error.

**Comment by DeepDiver1975** [comment]
Hard to tell. But please get in touch with the developers of the file storage adapter you are using
