### ISSUE TITLE
Inconsistent return type for \Sabre\DAVACL\PrincipalBackend\BackendInterface::findByUri

### ISSUE THREAD

**Issue by come-nc** [sabre-io/dav#1370]
Hello,

See the docblock for this function:
```
    /**
     * Finds a principal by its URI.
     *
     * This method may receive any type of uri, but mailto: addresses will be
     * the most common.
     *
     * Implementation of this API is optional. It is currently used by the
     * CalDAV system to find principals based on their email addresses. If this
     * API is not implemented, some features may not work correctly.
     *
     * This method must return a relative principal path, or null, if the
     * principal was not found or you refuse to find it.
     *
     * @param string $uri
     * @param string $principalPrefix
     *
     * @return string
     */
```

The comment says that the function may return null, but then there is `@return string` instead of `@return string|null`.
We implement it as returning `string|null` and this triggers psalm errors in our CI.

**Comment by DeepDiver1975** [comment]
As far as I can tell from implementing this interface as well: you should return and empty string instead of null.

**Comment by DeepDiver1975** [comment]
> * This method must return a relative principal path, or null, if the
>      * principal was not found or you refuse to find it.

doc wrong or annotation wrong? :see_no_evil:

**Comment by DeepDiver1975** [comment]
ah - already taken care of: https://github.com/sabre-io/dav/pull/1362

**Comment by come-nc** [comment]
> ah - already taken care of: #1362

In the abstract class, but not in the interface: https://github.com/sabre-io/dav/blob/master/lib/DAVACL/PrincipalBackend/BackendInterface.php#L115

**Comment by DeepDiver1975** [comment]
Feel free to submit a PR to address this - THX a lot
