### ISSUE TITLE
Fresh 4.3.0-installation has autoloader-problems

### ISSUE THREAD

**Issue by pk1234** [sabre-io/dav#1383]
Dear sabre experts,

I'm trying to upgrade our sabre dav 3.2.2 installation (running on an Apache 2.2.34 webserver with php 5.6.40 and MySQL 5.1.50) to sabre dav 4.3.0 with Apache 2.4.51, php 8.1.0 and MariaDB 10.6.5.

Sabre dav 3.2.2 was installed without composer. In 2017 I just unzipped a file into `<DocumentRoot>/SabreDAV-3.2.2` and created another directory `<DocumentRoot>/dav` where I placed `server.php` and 4 backends that we use to disable the SabreDAV user management and read user-information from our existing Oracle tables (and do some other stuff). Here's an extract from our `<DocumentRoot>/dav/server.php`:

```
...
require_once '../SabreDAV-3.2.2/vendor/autoload.php';
require_once 'naevAuth.php';
require_once 'naevPrincipal.php';
require_once 'naevCalendar.php';
require_once 'naevAddressBook.php';

$authBackend      = new \Sabre\DAV\Auth\Backend\naevAuth($pdo, $ora);
$principalBackend = new \Sabre\DAVACL\PrincipalBackend\naevPrincipal($pdo, $ora, $authBackend);
$carddavBackend   = new \Sabre\CardDAV\Backend\naevAddressBook($pdo, $ora);
$caldavBackend    = new \Sabre\CalDAV\Backend\naevCalendar($pdo, $ora, $authBackend);
$authBackend->setCalendarBackend($caldavBackend);

$nodes = [
  new \Sabre\CalDAV\Principal\Collection($principalBackend),
  new \Sabre\CalDAV\CalendarRoot($principalBackend, $caldavBackend),
  new \Sabre\CardDAV\AddressBookRoot($principalBackend, $carddavBackend),
];
$server = new \Sabre\DAV\Server($nodes);
$server->setBaseUri($prod ? "/dav/server.php" : "/dav.test/server.php");
$server->addPlugin(new \Sabre\DAV\Auth\Plugin($authBackend));
$server->addPlugin(new \Sabre\DAV\Browser\Plugin());
$server->addPlugin(new \Sabre\DAV\Sync\Plugin());
$server->addPlugin(new \Sabre\DAVACL\Plugin());
$server->addPlugin(new \Sabre\CalDAV\Plugin());
$server->addPlugin(new \Sabre\CalDAV\Schedule\Plugin());
$server->addPlugin(new \Sabre\CalDAV\Schedule\IMipPlugin('Kalender-Server@naev.de'));
$server->addPlugin(new \Sabre\CalDAV\ICSExportPlugin());
$server->addPlugin(new \Sabre\CardDAV\Plugin());
$server->exec();
...
```
Our new server is running, all of our own php-scripts were upgraded to php 8.1.0 and I installed sabre dav 4.3.0. I never used composer so far and composer was missing on the machine. Also the machine has no internet connection, so here are the commands I used on a different machine with internet-connection to create a `SabreDAV-4.3.0.tar` file:
```
cd /var/tmp
rm -rf SabreDAV-4.3.0
mkdir SabreDAV-4.3.0
cd SabreDAV-4.3.0
wget --no-check-certificate -O composer-setup.php https://getcomposer.org/installer
php composer-setup.php
php composer.phar require sabre/dav ~4.3.0
rm composer-setup.php composer.phar
cd ..
tar cf SabreDAV-4.3.0.tar SabreDAV-4.3.0
```
I then unpacked `SabreDAV-4.3.0.tar` into `<DocumentRoot>` of the new machine, copied `<DocumentRoot>/dav` from the old machine and replaced `SabreDAV-3.2.2` by `SabreDAV-4.3.0` in `server.php`

When opening `http://new.machine.de/dav/server.php` I get asked for my username/password and everything looks OK. But opening `http://new.machine.de/dav/server.php/calendars` does not work and shows the following error-message:
```
<d:error>
  <s:sabredav-version>4.3.0</s:sabredav-version>
  <s:exception>Error</s:exception>
  <s:message>Class "Sabre\HTTP\URLUtil" not found</s:message>
</d:error>
```
Seems like my installation is incomplete and some dependency is missing.

Any ideas, what I'm doing wrong? What happened to class URLUtil?

Kind regards

Peter

**Comment by DeepDiver1975** [comment]
> Any ideas, what I'm doing wrong? What happened to class URLUtil?

That class no longer exists and has been replaced with simple functions - see https://github.com/sabre-io/http/blob/315f592adfcba8aeb73c2fd64285205747acbbd7/lib/functions.php#L34

**Comment by pk1234** [comment]
Thanks DeepDiver1975!

So the good news are: my installation is complete and autoloading works. 

When we created our own principal-backend, we started with a copy of `vendor/sabre/dav/lib/DAVACL/PrincipalBackend/BackendInterface.php` and then replaced some of routines within that backend. The remaining routines were untouched.

Method getPrincipalsByPrefix from the 3.2.2-version of BackendInterface.php contains
```
list($rowPrefix) = URLUtil::splitPath($row['uri']);
```
And so does our principal-backend.

So instead of using our old Backends I must create fresh copies from the 4.3.0 sources and merge all modifications that we did 5 years ago.

This leads me to the question:  Were any of the interface-definitions changed since 3.2.2?

Peter

**Comment by DeepDiver1975** [comment]
> This leads me to the question: Were any of the interface-definitions changed since 3.2.2?

I cannot answer this right from my head - I fear you have to compare the versions yourself.

Generally speaking a TDD approach could help a lot when doing own coding .... ;-)

**Comment by pk1234** [comment]
> I cannot answer this right from my head - I fear you have to compare the versions yourself.

Just in case anybody is interested: I did not find any changes in the interface definitions between 3.2.2 and 4.3.0.
We will do some more testing and then our new server will replace the old one.

> Generally speaking a TDD approach could help a lot when doing own coding .... ;-)

I totally agree ;-)
And my next SabreDAV-activity will be to write some unit-tests for issue #1250
