### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class "Sabre\DAV\FS\Directory" not found in /var/www/html/mail.domain.com/server.php:9

### ISSUE THREAD

**Issue by EvanTheProgrammer** [sabre-io/dav#1395]
I am trying to setup a basic DAV server so i setup nginx with PHP 8.1 and i can load PHP info and i am able to run `composer require sabre/dav` but when i use the example code
```php
<?php
use
    Sabre\DAV;

// The autoloader
require 'vendor/autoload.php';

// Now we're creating a whole bunch of objects
$rootDirectory = new DAV\FS\Directory('public');

// The server object is responsible for making sense out of the WebDAV protocol
$server = new DAV\Server($rootDirectory);

// If your server is not on your webroot, make sure the following line has the
// correct information
$server->setBaseUri('/server.php');

// The lock manager is reponsible for making sure users don't overwrite
// each others changes.
$lockBackend = new DAV\Locks\Backend\File('data/locks');
$lockPlugin = new DAV\Locks\Plugin($lockBackend);
$server->addPlugin($lockPlugin);

// This ensures that we get a pretty index in the browser, but it is
// optional.
$server->addPlugin(new DAV\Browser\Plugin());

// All we need to do now, is to fire up the server
$server->exec();
?>
```
But when i do `php server.php` but it gives me the error `PHP Fatal error:  Uncaught Error: Class "Sabre\DAV\FS\Directory" not found in /var/www/html/mail.domain.com/server.php:9` aswell as going to the browser just gives a blank page.

**Comment by DeepDiver1975** [comment]
Is the path in the require statement correct?

This all sounds like basic usage issues of php and composer.

**Comment by EvanTheProgrammer** [comment]
yes there is a vendor/autoload.php file where the php file is if this is wrong what am i supposed to do as i was following the docs.

**Comment by sschleic** [comment]
Sorry for comming back to the question of @EvanTheProgrammer:
I'am running into the same problem:
1. I installed sabre/dav with composer into my webroot directory
2. I copied the example calendarserver.php to the webroot directory
3. I adapted the database connection
4. But after access calendarserver.php with the webbrowser I'am getting the "Uncaught Error: Class "Sabre\DAV\FS\Directory" not found" error

@EvanTheProgrammer the you manged it? Could you please face me to the right direction?
I triple checked the permissions.
