### ISSUE TITLE
Is 3.2.3 still the current official version

### ISSUE THREAD

**Issue by escix** [sabre-io/dav#1397]
Hi,

As per the fruux sabre.io website version 3.2.3 is the last version released for sabre/dav.
Is 3.2.3 the latest official version or the website is outdated?.

I am trying to port sabre/dav to freebsd but there is a feeling that 4.3.1 is still development and not official.

Can you please clarify.

**Comment by DeepDiver1975** [comment]
4.3.1 is latest version see https://github.com/sabre-io/dav/releases



> I am trying to port sabre/dav to freebsd

what exactly is there to be done? sabre/dav is written in php which abstracts all os/distro specific things  ..... :confused:
