### ISSUE TITLE
CardDav: ACL hard to set to readOnly

### ISSUE THREAD

**Issue by mokraemer** [sabre-io/dav#1399]
I think many implementations deal with the struggle to just serve readonly access to adressbooks. You can for sure just deny all writes and throw exceptions. But it would be nice to have an easy way to set the adressbook readonly, so the client knows it can't modify.

If I'm right, the acl for an adressbook is always set to
{DAV:}all

Even for the cards themself it is hard to set, since in the database backend "principaluri" is not passed to getCard/getCards.

**Comment by DeepDiver1975** [comment]
you can use a different folder which a different set of plugins to allow this.

`calendars/$user/cal1` is the private endpoint for the user with full access and it requires auth
`public-calendars/cal1` can be read only without auth being required...




> Even for the cards themself it is hard to set, since in the database backend "principaluri" is not passed to getCard/getCards.


maybe some idea on this: 
https://github.com/owncloud/core/blob/ab9763b2b4d27a221bf12005eddd2bb7d319d286/apps/dav/lib/CardDAV/AddressBook.php#L74
