### ISSUE TITLE
Should I implements DAV\IMoveTarget on File Node?

### ISSUE THREAD

**Issue by augushong** [sabre-io/dav#1400]
My node class files like this.

fs                
├─ Directory.php  
├─ File.php       
└─ Node.php       

![图片](https://user-images.githubusercontent.com/31880431/170454950-18f51148-a4b7-4f19-9544-db1cf7e7e4fd.png)

If I want to implements DAV\IMoveTarget , Should I implements DAV\IMoveTarget on File Node?

Or Just implements in Directory.php  is fine.

**Comment by DeepDiver1975** [comment]
IMoveTarget implements ICollection - this means it is on folder only
