### ISSUE TITLE
is that getQuotaInfo include all depth files in collection，but {DAV：quotaUsedBytes} just need 1 depth?

### ISSUE THREAD

**Issue by augushong** [sabre-io/dav#1402]

**Comment by DeepDiver1975** [comment]
https://github.com/sabre-io/dav/blob/055e2edce01fe942442fca2eb8b3ddb0239de219/lib/DAV/FS/Directory.php#L138

https://github.com/sabre-io/dav/blob/b282db90527cf74bfa010f29f6f9b88b3ffd0257/lib/DAV/CorePlugin.php#L763
