### ISSUE TITLE
Mangles vcards with diacritics

### ISSUE THREAD

**Issue by mbiebl** [sabre-io/dav#1405]
I have a vCard like the following:
```
BEGIN:VCARD
VERSION:3.0
UID:F0-F3-D8-A4-EC-0A-34-F2-B2-AE-53-35-FB-F0-57-C5
N:Hatschek;ž;;;
FN:ž Hatschek
END:VCARD
```
The problem is in https://github.com/sabre-io/dav/blob/master/lib/DAV/StringUtil.php#L78

For some reason mb_detect_encoding() thinks the file is in ISO-8859-1 format and the re-encodes it as UTF-8.
This results in ž being turned into Å¾

**Comment by DeepDiver1975** [comment]
should be fixed with - https://github.com/sabre-io/dav/pull/1404

@mbiebl can you test?

**Comment by mbiebl** [comment]
The result is weird though:
`mb_check_encoding($input, 'UTF-8')` on the above file is true.
`mb_check_encoding($input, 'ISO-8859-1')` on the above file reports true as well.

**Comment by mbiebl** [comment]
I.e. the above data is not ISO-8859-1

**Comment by mbiebl** [comment]
@DeepDiver1975 I'm a bit sceptical about the results of mb_*_encoding and the automatic re-encoding.

How do you feel about making this re-enconding optional?

**Comment by mbiebl** [comment]
Yeah, #1404 certainly improves the situation. 
That said, if you are in a situation where you can control the input data and know it's valid UTF-8, avoiding the detection-and-automatic-re-encoding would prove to be useful, I think.

**Comment by phil-davis** [comment]
> That said, if you are in a situation where you can control the input data and know it's valid UTF-8, avoiding the detection-and-automatic-re-encoding would prove to be useful, I think.

The new code checks 
`!mb_check_encoding($input, 'UTF-8') && mb_check_encoding($input, 'ISO-8859-1')`

If `mb_check_encoding` agrees that it looks like valid UTF*, then the logic evaluation if the `if` statement will stop there. It goes to the `else` and returns the input string without encoding/decoding it.

**Comment by mbiebl** [comment]
Well, that assumes that `mb_check_encoding($input, 'UTF-8')` always correctly detects UTF-8.

**Comment by DeepDiver1975** [comment]
seems to be fixed -> close
