### ISSUE TITLE
New release 4.4.0 because of merged code

### ISSUE THREAD

**Issue by mmattel** [sabre-io/dav#1406]
Code has been merged, see https://github.com/sabre-io/dav/pull/1396

A new official release would help a lot for our projetcs to use it - how to proceed? Many thanks.

@DeepDiver1975 @jvillafanez @phil-davis fyi

**Comment by phil-davis** [comment]
I have done the other "easy" ones:
https://github.com/sabre-io/http/releases/tag/5.1.4
https://github.com/sabre-io/cache/releases/tag/1.0.4
https://github.com/sabre-io/vobject/releases/tag/4.4.2

I will try to dig through what has happened here in `dav` tonight, merge whatever can easily be merged, and publish a new release...

**Comment by phil-davis** [comment]
PR #1407 prepares for release 4.4.0

**Comment by phil-davis** [comment]
4.4.0 released https://github.com/sabre-io/dav/releases/tag/4.4.0
