### ISSUE TITLE
Problem with invalid XML 1.0 character from VCS in CardDAV

### ISSUE THREAD

**Issue by pboguslawski** [sabre-io/dav#1412]
Please take a look at

https://github.com/nextcloud/contacts/issues/2797#issuecomment-1198222897

in case it's wider problem with Sabre CardDAV implementation (Nextcloud seems to use Sabre for CardDAV handling).

**Comment by DeepDiver1975** [comment]
THX for letting us know - I am pretty sure nextcloud devs will reach out to us if there is anything to fix.
Most probably they will even provide a fix as they did in the past.

Closing this here for the time being.
