### ISSUE TITLE
The recursion in getChildren fails if there are no children.

### ISSUE THREAD

**Issue by captainwasabi** [sabre-io/dav#1413]
The real underlying bug may ultimately be in my data, but in Tree.php around line 200 throws the recursive call to $node->getChildren() throws a fatal exception.  I'm using nextcloud, and after a migration it's throwing fatal exceptions when processing empty directories.  I put the entire foreach clause in a try/catch clause and that cleared up the problem.  I didn't submit a PR because I'm not a php programmer and have no experience with this library, so there is likely a better way to do this.

**Comment by DeepDiver1975** [comment]
Please report this to nextcloud
