### ISSUE TITLE
Feature request: Multipart byte ranges

### ISSUE THREAD

**Issue by DanRiess** [sabre-io/dav#1416]
Hey guys, 
not sure if this is the right spot for this kind of question, but is it possible to allow multipart byte range requests?
Currently, if I'm not misreading your code, only one range per request is accepted and handled.

'Range: bytes=123-456' is allowed and will be processed
'Range: bytes=123-456, 789-1234' will be blocked and the whole file will be send instead

I'm using NextCloud to work with binary files that are chunked into very small parts. I only ever need about 1/3 of the files, but that third may be multiple dozens of chunks and it would be nice to be able to bundle them together instead of having to send one request per chunk.

**Comment by DeepDiver1975** [comment]
Currently only a single range is supported. Thinking about the backend implementations (e.g in ownCloud and nextcloud) this can be quite challenging.

Never the less feel free to submit a PR. THX
