### ISSUE TITLE
How to deal with sabredav and IMIP's ics?

### ISSUE THREAD

**Issue by MIKOTO123** [sabre-io/dav#1417]
As a webmail client, I don't know how to operate sabredav after receiving an invitation that from other service,even how to deal with imip's ics. The RFC is inarticulate and has no example.Who can give me some suggestions?

**Comment by DeepDiver1975** [comment]
Sabre dav is sending out imip via email and mail clients can detect the mime type `text/calendar` and import the ics into the linked calendar software. 
Usually the user is asked to choose a calendar to import.
If the calendar software supports CalDAV - a simple put of the ics to the calendar will import the data.

hope this helps.

https://github.com/sabre-io/dav/blob/b336bece918f8ba0061043761eee49b6c9700228/lib/CalDAV/Schedule/IMipPlugin.php#L154
