### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by superpuffin** [sabre-io/dav#1428]
Currently the documentation on sabre.io still recommends installing v3 and lists it as the latest version and currently supported. This can make the project seem stale, whist it is actively developed.

**Comment by TerryvanWalen** [comment]
I am very interested to learn how to upgrade from version 3.1 (or 3.2) to master/4.x.

**Comment by phil-davis** [comment]
Release 4.0.0 https://github.com/sabre-io/dav/releases/tag/4.0.0
Here are PRs done in the past by consumer projects when they updated to dav 4.0:
https://github.com/owncloud/core/pull/34559
https://github.com/nextcloud/server/pull/19325

Those will have some clues about what backward-compatibility issues caused consumer code to need to be adjusted.

AFAIK the people actively maintaining the `sabre/dav` (`sabre/vobject` `sabre/http` ...) repos do not have access to the sabre.io web site. I am not sure how that will ever get maintained/updated.

**Comment by TerryvanWalen** [comment]
Amazing! That is a good starting point. Thanks @phil-davis .

**Comment by marcelstoer** [comment]
I ended up here since I was looking for instructions how to up _date_ (not upgrade) from 4.0.x to the latest.

> AFAIK the people actively maintaining the sabre/dav (sabre/vobject sabre/http ...) repos do not have access to the sabre.io web site.

Can you elaborate on this please. It left me a bit puzzled. The recent committers _here_ are either you or @DeepDiver1975 - both of whom committers at the https://github.com/sabre-io/sabre.io repo as well 😄

**Comment by joshtrichards** [comment]
@marcelstoer I suspect it has to do with this: https://github.com/sabre-io/sabre.io/issues/138

**Comment by phil-davis** [comment]
I have pinged Dominik again here:
https://github.com/sabre-io/sabre.io/issues/138#issuecomment-1683350386

And made a bunch of typo fixes in PR https://github.com/sabre-io/sabre.io/pull/151

Let's see if anything gets to the web site.

**Comment by DeepDiver1975** [comment]
temp solution https://sabre-io.github.io/sabre.io/
