### ISSUE TITLE
Webdav sharing files or folders  ...

### ISSUE THREAD

**Issue by phili67** [sabre-io/dav#1433]
I'm searching informations on :
- sharing folders
- sharing files 

to others users.

I've added :
```$server->addPlugin(new Sabre\DAV\Sharing\Plugin());```

It's written :
The biggest thing you will need to do, is add support for **Sabre\DAV\Sharing\ISharedNode** to your custom filesystem nodes.

But how ?

Could you give me some advices ?

Philippe

**Comment by DeepDiver1975** [comment]
Sabre's sharing plugin is designed to work with caldav - refs draft-pot-webdav-resource-sharing

It cannot really be used for files and folders.

It you are looking for a file sharing solution: check out owncloud, nextcloud, pydio, seafile or any of the well known open source files sharing solutions.

**Comment by DeepDiver1975** [comment]
ISharedNode is implemented in SharedCalendar

https://github.com/sabre-io/dav/blob/c1afdc77a95efea6ee40c03c45f57c3c0c80ec22/lib/CalDAV/ISharedCalendar.php#L16
https://github.com/sabre-io/dav/blob/c1afdc77a95efea6ee40c03c45f57c3c0c80ec22/lib/CalDAV/SharedCalendar.php#L16
