### ISSUE TITLE
Documentation does not match actual information about download

### ISSUE THREAD

**Issue by JRSofty** [sabre-io/dav#1462]
Since I'm not the type of person to install a software to deploy a PHP application in my webserver, I would like to attempt an install using the tarball that is included in the 4.4.0 release. 

According to the documentation there is a required `vendor/autoload.php` file and it states

> Make sure you know what the exact path is to vendor/autoload.php. If you did the composer install, it should be in your current directory. If you used the zip, **it will be where ever you unpacked the zip**.

Interestingly enough this file is no where to be found where I unpacked the zip file.

Is there any existing documentation on how to properly install this application by hand, without the use of `composer`?

**Comment by evert** [comment]
The tarballs are just source snapshots. I dont think the zips have been generated in years.

The way those used to be built was by downloading the source and running composer. If you do that and tar the result you will get what you need.
