### ISSUE TITLE
Microsoft Office 365 alert about webdav connection ?

### ISSUE THREAD

**Issue by guldil** [sabre-io/dav#1466]
Hello

Today i have a new errr while opening a excel file from a webdav server.

https://support.microsoft.com/en-us/topic/microsoft-office-will-block-this-file-because-it-uses-a-sign-in-method-that-may-be-unsecure-a7c31d0d-ef2c-4760-bf66-505e9667c6fe

Do you think it's something i can fix with my sabreDAV implementation or it's a problem with Windows WebDav Client ?

Thanks

Guldil

**Comment by DeepDiver1975** [comment]
depends on what M$ defines as 'Modern Authentication'.

Without looking into the details - I assume they are talking about OpenID Connect or OAuth.

This can be implemented using the Bearer auth backend - https://github.com/sabre-io/dav/blob/master/lib/DAV/Auth/Backend/AbstractBearer.php

But you require an IdP to authenticate with.

All in all: not easy and beyond any support we can give here.

Good luck
