### ISSUE TITLE
Unable to login with principals/username 

### ISSUE THREAD

**Issue by jatinvishwa** [sabre-io/dav#1476]
While accessing the URL http://localhost/caldav/principals/jv@codecracky.com/
Getting this error: 
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>3.2.2</s:sabredav-version>
<s:exception>PDOException</s:exception>
<s:message>SQLSTATE[HY000]: General error: 10 disk I/O error</s:message>
</d:error>

**Comment by DeepDiver1975** [comment]
> 3.2.2

This is about 5 years old - you better use the latest code base

> SQLSTATE[HY000]: General error: 10 disk I/O error

You are obviously using sqlite - things like this can happen with sqlite when being used in a web application due to concurrent access and such.

Migrate to mysql

**Comment by jatinvishwa** [comment]
Can you provide me with the latest code base
