### ISSUE TITLE
Coupling Mode

### ISSUE THREAD

**Issue by flavi1** [sabre-io/dav#1485]
Just an idea to get discussed. Example :
A DAV Server is available on **dav.example.com/**
a web server is available on **www.example.com/**
The developper wants to give html representation of the files and folder.
**www..example.com//folder** is a html representation of the **dav.example.com//folder** collection.
**www..example.com//file.txt** is a html representation of the **dav.example.com//file.txt** file, or a direct link to download the file, depending of its mimetype or of what want to provide the developper.
The developper would like, for example, to be able to process a PROPFIND and inject values in a template. Or make possible to send a file by an input type file html element or other drag and drop.
This is already possible by using the DAV client and the DAV server on the same machine.
The idea is to avoiding the HTTP process in this case. For example, instead of give an URL to the client, I can give a DAV server instance directly.
Or, implementing PSR-15 can do the job, since I can easily intercept requests and response in my own way.
Continue to use DAV client Server to got it is good since my File System is likely to be "Virtual", and already provide a full ACL management.
Since the same HTTP/Request and Response are used by both client and Server, I assume (not sure) that it is probably not hard to implement. Probably just by getting response and request object, and use the send method later in each sides (like with a PSR-15 middleware).
A later more optimized, but maybe more complicated is to give a more direct internal relation that can skip the XML create and parse process. Get the response as array instead of its XML end representation can allow the developper to inject it as a template variable and win a lot of time, avoiding the re-parsing need 
(sorry for my english)

**Comment by DeepDiver1975** [comment]
Not sure what your expectation of this issue is .... feel free to build what ever you like ;-)
