### ISSUE TITLE
A lot of "File $path could not be located" warnings, when using Windows Explorer

### ISSUE THREAD

**Issue by Offerel** [sabre-io/dav#1494]
In the logfile of my SabreDAV implementation I have an incredibly large amount of messages with "File could not be located". According to the log file, these are caused exclusively by a user agent "Microsoft-WebDAV-MiniRedir/10.0.22000". I suspect this is the Windows Explorer. Since all files are present and I can't see from the error message which file is supposed to be missing, I looked where this message comes from. I found it in [/lib/DAVACL/FS/Collection.php](https://github.com/sabre-io/dav/blob/a74464d583af69d72106ad48820b52bb44144e43/lib/DAVACL/FS/Collection.php#L69). I have adapted the function therefore a little:

```
    public function getChild($name)
    {
        $path = $this->path.'/'.$name;

        if (!file_exists($path)) {
            throw new NotFound("File $path could not be located");
```

Now I can see that desktop.ini is searched for and per node entry by filename.ext.ws

These files are of course not present. Why Windows Explorer is looking for them is completely unclear, at least to me. Do you have an explanation or advice how I can disable this behavior in Windows Explorer? Or is there a way to prevent this behavior on the server side?

**Comment by DeepDiver1975** [comment]
A 404/Not Found is a quite normal response to request for resources which are not known aka do not exist.

Looks like Windows explorer is expecting desktop.ini to exist - but it doesn't. My assumption is that Explorer knows what to do in this scenario.

All cool from my understanding ....



> advice how I can disable this behavior in Windows Explorer?

no - sorry



> Or is there a way to prevent this behavior on the server side?

no - see above ...

**Comment by Offerel** [comment]
Windows Explorer seems to be the only client with this behavior. Normally i don't use Windows (I'm a poor Arch-Linux Fan), but on work, i have no other choice... I can a little bit understand the desktop.ini thing, but what are this *.ws files? For example on the WebDAV Share it exists a file with the name testfile.txt, so Windows Explorer does list this file and try to search additionally for a file testfile.txt.ws

What ever this is...

I don't know if there a Microsoft Experts, how can answer this question. As long, as i don't know, what this *.ws file does or what's the meaning of it, i cant research by myself in the whole Internet :-)

BTW: Is there a other way beside my small change in Collection.php, to see the requested filename in the exception? Currently im using something like:

$server->on('exception', function(Exception $e) {
    $message = $e->getMessage();
}

to get the error message. But it would be nice to get the filename like 'desktop.ini' or 'testfile.txt.ws' with another property.

**Comment by DeepDiver1975** [comment]
You can wrap the exception logging logic into your own plugin - as example: https://github.com/owncloud/core/blob/5cb4d66451aa45f05a9728fee74902120f94a5e2/apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php#L87

**Comment by Offerel** [comment]
OK. many thx. I will have a look in to this. For the Windows Explorer question, I will raise a ticket on Microsoft. I will update this issue, if i get a useful response. In the meantime, i close this issue.
