### ISSUE TITLE
Sabre\\DAV\\Exception\\NotAuthenticated with no apparent detail

### ISSUE THREAD

**Issue by Aonodensetsu** [sabre-io/dav#1530]
I have the following Sabre error in my Nextcloud server, I have no idea when it appeared, but I'm on NC 28.0.1.
Logging in works fine, but this error appears in the logs when opening any external share, immediately refreshing said page (which throws again, ad inifitum).

``{"reqId":"ftYo2YCg5dgMPUqSKQgA","level":0,"time":"December 29, 2023 19:47:55 +0000","remoteAddr":"10.0.0.1","user":"--","app":"webdav","method":"PROPFIND","url":"/public.php/webdav/","message":"Exception thrown: Sabre\\DAV\\Exception\\NotAuthenticated","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0","version":"28.0.1.1","exception":{"Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/ServerFactory.php","line":133,"function":"{closure}","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"OCA\\DAV\\Connector\\Sabre\\{closure}","class":"OCA\\DAV\\Connector\\Sabre\\ServerFactory","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":456,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php","line":124,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/public.php","line":81,"args":["/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php","Line":81,"message":"","exception":{},"CustomMessage":"Exception thrown: Sabre\\DAV\\Exception\\NotAuthenticated"}}``

I don't know what to troubleshoot, so I thought coming here is the most logical followup.

**Comment by DeepDiver1975** [comment]
Please reach out to the nextcloud devs about this.
