### ISSUE TITLE
How can I delete all resources in CalDAV calendar collection

### ISSUE THREAD

**Issue by monkeyfdude** [sabre-io/dav#1543]
* I am not a **sabre/dav** user yet.

* I am trying to delete all resources in CalDAV calendar collection
* I use `curl -k --user "user1:pwd1" -X DELETE -H "Content-Type: text/calendar; charset=utf-8" "http://example.com:8008/calendars/users/user1/calendar/`
* I see the all the resources removed and calendar collection not accessible anymore
* But, when I try to create an event again using **`"PUT"`**, I get `error code 409`
* I even tried re-creating that account like a new account.

* Would you be able to tell me the right way to delete all resources in a calendar collection?

**Comment by DeepDiver1975** [comment]
unrelated to sabre dav - more a general webdav question ...

webdav does not have an option to perform a delete all
