### ISSUE TITLE
CardDAV server is broken when using iOS 17.3.1

### ISSUE THREAD

**Issue by sw030453** [sabre-io/dav#1546]
After **_many years_** of faithful service, my CalDAV/CardDAV server seems broken.  I keep getting messages like this in the log:

> xx.xx.xx.xx - - [06/Mar/2024:10:18:33 -0800] "REPORT /i/card.php/addressbooks/stevewi/Test/ HTTP/1.1" 500 345 "-" "iOS/17.3.1 (21D61) dataaccessd/1.0"

(note the HTTP 500 error) and the Contacts on the phone don't sync...even though the phone connects to the contacts account just fine.  It seems to work fine on my Mac (Sonoma -- 14.3.1 -- 23D60].  Calendars seem to work just fine on both as well.

I'm using:

> FreeBSD 14.0-RELEASE-p5  (uses OpenSSL 3.0.13)
> php 8.3.3 (with php-fpm...I use a multi-threaded web server)
>
>     -  php83-composer-2.7.1
>     -  php83-ctype-8.3.3
>     -  php83-curl-8.3.3
>     -  php83-dom-8.3.3
>     -  php83-fileinfo-8.3.3
>     -  php83-filter-8.3.3
>     -  php83-iconv-8.3.3
>     -  php83-intl-8.3.3
>     -  php83-mbstring-8.3.3
>     -  php83-opcache-8.3.3
>     -  php83-pcntl-8.3.3
>     -  php83-pdo-8.3.3
>     -  php83-pdo_sqlite-8.3.3
>     -  php83-phar-8.3.3
>     -  php83-posix-8.3.3 
>     -  php83-session-8.3.3
>     -  php83-simplexml-8.3.3
>     -  php83-sqlite3-8.3.3
>     -  php83-tokenizer-8.3.3
>     -  php83-xml-8.3.3
>     -  php83-xmlreader-8.3.3
>     -  php83-xmlwriter-8.3.3
>     -  php83-zip-8.3.3
>     -  php83-zlib-8.3.3
>
> sabre/dav v4.6.0
> sabre/event v5.1.4
> sabre/http v5.1.10
> sabre/uri v2.3.3
> sabre/vobject v4.5.4
> sabre/xml v2.2.6
> psr-4

I've attached the source of **_card.php_** for your reference as well (it's pretty short and simple).  The database is SQLite and uses the vanilla schema shipped with the sabre-io examples.  The schema is attached as well.

I'm really at a loss about what's causing this or where to look for it.  I'm also **_NOT_** discounting the fact that this is an iOS bug (it wouldn't be the first time for one of these).

If any of you have any insights, I'd surely appreciate you passing them on to me.  Thanks in advance...

[card.php.txt](https://github.com/sabre-io/dav/files/14514254/card.php.txt)
[db.schema.txt](https://github.com/sabre-io/dav/files/14514259/db.schema.txt)

**Comment by sw030453** [comment]
Here are the values of the various constants used in **_card.php_**:
```
DavAdmin\Constants\Time::ZONE = "America/Los_Angeles";
DavAdmin\Constants\Database::ID = "sqlite:///srv/ical/var/db/davsyncdb.sqlite";
DavAdmin\Constants\Server::REALM = "Shared";
```

**Comment by DeepDiver1975** [comment]
http status code 500 indicates some backend error - please have a look at the web server logs if you see more details.

**Comment by sw030453** [comment]
There are no entries in the web server/php-fpm logs corresponding to this.
```
stevewi:/var/log/httpd $ grep '06\/Mar\/2024:10:18' httpd-access.log
stevewi:/var/log/httpd $ grep '06\/Mar\/2024:10:18' httpd-error.log
stevewi:/var/log/php-fpm $ grep '06\/Mar\/2024:10:18' php-fpm.log
stevewi:/var/log/httpd $ grep '500' httpd-access.log
stevewi:/var/log/httpd $ grep '500' httpd-error.log
stevewi:/var/log/php-fpm $ grep '500' php-fpm.log
```

This is another reason this is so puzzling.

**Comment by DeepDiver1975** [comment]
Grep for "Exception"

**Comment by sw030453** [comment]
```
stevewi:/var/log/httpd $ grep 'Exception' httpd-access.log
stevewi:/var/log/httpd $ grep 'Exception' httpd-error.log
stevewi:/var/log/httpd $ grep 'Exception' ical.access.log.2024.03.06
stevewi:/var/log/httpd $ grep 'Exception' ical.error.log.2024.03.06
stevewi:/var/log/php-fpm $ grep 'Exception' php-fpm.log
```

**Comment by sw030453** [comment]
iOS 17.4 became available today.  I just updated my phone.  Same results  :-(

**Comment by DeepDiver1975** [comment]
Without any detailed error message it is hard to tell what is causing the issue .....

**Comment by sw030453** [comment]
Until *sabre* generates an error, it is hard to give you what you want...

**Comment by DeepDiver1975** [comment]
> Until _sabre_ generates an error, it is hard to give you what you want...

you might have missed to setup the logger properly.
Server implements the LoggerAwareInterface https://github.com/sabre-io/dav/blob/da8c1f226f1c053849540a189262274ef6809d1c/lib/DAV/Server.php#L26C25-L26C45

example code:
https://github.com/sabre-io/dav/blob/da8c1f226f1c053849540a189262274ef6809d1c/examples/groupwareserver.php#L55-L56
https://github.com/sabre-io/dav/blob/da8c1f226f1c053849540a189262274ef6809d1c/examples/groupwareserver.php#L80-L81
