### ISSUE TITLE
allowAccessToNodesWithoutACL - Missing IACLs

### ISSUE THREAD

**Issue by bravedave** [sabre-io/dav#1547]
I can see this has been discussed before in issue #788, and the code appears to work

But in [PHP 8.2: Dynamic Properties are deprecated](https://php.watch/versions/8.2/dynamic-properties-deprecated)

the documentation at https://sabre.io/dav/acl/

has an example:
```php
    $aclPlugin = new \Sabre\DAVACL\Plugin();
    $aclPlugin->allowAccessToNodesWithoutACL = false;
```
_allowAccessToNodesWithoutACL_ is an undefined property

Issue #788 mentions there is another way to do it
* https://github.com/sabre-io/dav/issues/788#issuecomment-189923935 seems to show how to do it

so the question is - what would be the correct way to do it now ?

**Comment by DeepDiver1975** [comment]
from the changelog in the original change back in 2016: https://github.com/sabre-io/dav/pull/815/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR25
