### ISSUE TITLE
Some cleanup and improvements for Sabre_HTTP_Util

### ISSUE THREAD

**Issue by evert** [sabre-io/dav#181]
_Original author: 1me...@gmail.com (November 10, 2010 07:46:37)_

I removed some unnecessary escaping and replaced the check for GMT with a little more efficient strpos rather than using preg_match.
Does not alter the functions behavior in any way, just makes it a little more readable.

http://code.google.com/r/1meref-sabredav-amazons3/source/detail?r=4d4ffddc3e4f3da577e33cf5ea9973d8e593ca97

_Original issue: http://code.google.com/p/sabredav/issues/detail?id=109_

**Comment by HazCod** [comment]
@evert; is the author still available? I have interest in his project as it adds S3 support to sabre-dav.

**Comment by evert** [comment]
It looks like the archive is here:

https://code.google.com/archive/p/1meref-sabredav-amazons3/

**Comment by evert** [comment]
I did an export to github:

https://github.com/evert/1meref-sabredav-amazons3

No idea what the state of this is. Likely needs to have a fair bit of upgrades since the code is 5 years old.
