### ISSUE TITLE
PROPFIND variable depth and infinity depth support

### ISSUE THREAD

**Issue by evert** [sabre-io/dav#262]
_Original author: stefano....@gmail.com (April 12, 2012 09:14:26)_

<b>What steps will reproduce the problem?</b>
1.A PROPFIND request with any depth different from 1 is always treated as a 1 depth PROPFIND

<b>What is the expected output? What do you see instead?</b>
PROFIND requests for depth greater than 1 should return the webdav share tree from the given path to the given depth, or the complete tree from the given path if 'infinity' depth is given.

The attached file contains a patch to the Sabre/Dav/Server.php class to recursively walk down the fs tree to the given depth or to infinity.

_Original issue: http://code.google.com/p/sabredav/issues/detail?id=204_

**Comment by martinvonwittich** [comment]
FTR, here is the PR if anyone else is looking for it: [Introduce depth infinity for PROPFIND by DeepDiver1975 · Pull Request #398 · sabre-io/dav [github.com]](https://github.com/sabre-io/dav/pull/398)
