### ISSUE TITLE
URLUtil::encodePath[Segment]() incorrectly encode colons

### ISSUE THREAD

**Issue by yunosh** [sabre-io/dav#374]
Subject says it all. Colons are perfectly valid in URI/URL paths and must not be encoded when returned in response-hrefs.

**Comment by Xenopathic** [comment]
Not encoding colons seems to break ownCloud synchronisation: owncloud/core#23740

Reading http://www.ietf.org/rfc/rfc1738.txt it seems that any reserved characters should be encoded in a URL? That includes the colon

**Comment by evert** [comment]
Could you open a fresh ticket for this at https://github.com/fruux/sabre-uri/issues ? Annoying problem :(
