### ISSUE TITLE
Error message on failed auth

### ISSUE THREAD

**Issue by benrubson** [sabre-io/dav#412]
Hello,

I would like to have error messages in my Apache error.log, when authentication fails.
Really useful to work against attacks, with fail2ban for example.

So here is how I modified AbstractDigest.php, I just added error_log function 3 times :
http://pastebin.com/raw.php?i=kvhiY2Lh

Could we think about adding this patch to the next SabreDAV release ?
However, perhaps a cleaner (and working) solution exists, if ever error_log has been disabled in php.ini ?

Thank you very much !

Best regards,

Ben

**Comment by benrubson** [comment]
Hello Evert,

Any news about the getUserName() implementation ?
I couldn't find it in the changelog.

Thank you very much !

Best regards,

Ben

**Comment by benrubson** [comment]
Hi @evert, is the `$server->on()` syntax above still valid ?
I tried to add it to last Baikal release, in `dav.php`, but then I get :
`Call to undefined method Baikal\Core\Server::on()`

Many thx 👍

**Comment by DeepDiver1975** [comment]
@benrubson I have no idea about Baikal - but Evert is talking about the DAV\Server not Baikal\Core\Server. Hope this helps.

**Comment by benrubson** [comment]
Yes it helped @DeepDiver1975, thank you 👍 
I placed the piece of code into `initialize()`, `dav/lib/DAV/CorePlugin.php`, and it works as expected.
Thank you !
