### ISSUE TITLE
Auth/Backend/Apache: We did not receive the $_SERVER[REMOTE_USER] property ...

### ISSUE THREAD

**Issue by voxspox** [sabre-io/dav#558]
Hi,

I installed SabreDAV 2.0.5 and setup Basic Auth in my .htaccess and https. Also I put the code for using the Apache auth backend into my server.php (according to the getting started documentation).

Accessing the page via browser I get the error message:
We did not receive the $_SERVER[REMOTE_USER] property. This means that apache might have been misconfigured.

This exception is thrown in Backend/Apache.php if getRawServerValue('REMOTE_USER') gives no results. I checked $_SERVER and there was no REMOTE_USER but there is a REDIRECT_REMOTE_USER. I don't know why there is a redirect.
Using this variable it works.

knut

**Comment by voxspox** [comment]
some more info:
according to the PHP manual
http://php.net/manual/en/reserved.variables.server.php
the proper variable seems to be PHP_AUTH_USER

**Comment by evert** [comment]
`PHP_AUTH_USER` doesn't work for every SAPI. It mainly works with Apache + mod_php. However, if `PHP_AUTH_USER` is set it will be picked up by the plugins.
