### ISSUE TITLE
OAUTH2 authentication

### ISSUE THREAD

**Issue by clarktlaugh** [sabre-io/dav#854]
Is anyone working on OAUTH2 authentication / is it planned for an upcoming release?  This is something I am very interested in and can possibly work on it in the future.
##

**Comment by evert** [comment]
We currently have an abstract auth backend for the OAuth2 bearer token.
If you want to make this a true feature request, i think it would be really helpful if you could in more detail describe what your goals are, or what sabre/dav does after implementing the OAuth2 feature you want.

Having OAuth2 support can mean a wide range of things for a lot of different people.

**Comment by clarktlaugh** [comment]
My goal would be for a user to be able to obtain a token from Google, Facebook, etc. which could be provided to sabre/dav for authentication instead of a username / password.  Similar to what is now required to access Google's CardDAV APIs.  It would probably need to be done in conjunction with a "whitelist", or some kind of extensible verification interface to only allow access to specific users.

I have recently implemented a similar authentication mechanism for a Meteor application I just wrote.  After receiving the result of the authentication attempt from the OAuth2 provider, I validate that the user is in an approved list.  If not, the login request is rejected.

**Comment by evert** [comment]
Based on a token alone the server can't really figure out which OAuth provider to validate against though right? Would this mean you need different verification endpoints for every provider?

Anyway, sounds interesting. If you are willing to work on this I can keep this ticket open but will likely close it if I feel it's not really happening.

In either case I think it would be good for a feature like this to have a bit more specification and I would also recommend you write down the approach you'll take in terms of buildings this, so I'll be able to tell you early if it's the correct path.

**Comment by clarktlaugh** [comment]
Yes - My understanding is that you'd have to know who to verify the token with.  I can not work on it right now, but I will hopefully have the opportunity soon.  My hope was that I would find someone else was already in the process of working on it as well and I'd be able to help.
