### ISSUE TITLE
Authenticating SabreDAV endpoint using OAuth2 / SAML

### ISSUE THREAD

**Issue by speidy** [sabre-io/dav#927]
Hello all.

Thanks for your great work.

I'm trying to figure out whether I can do OAuth2 / SAML authentication against SabreDAV server
So users can access their WebDAV files only if authenticated using those protocols.

I'm actually using [NextCloud](https://nextcloud.com/) system which using SabreDAV in order to provide WebDAV access to files.

Additionally, I thought about leveraging cookies in order to transfer the auth tokens  to the server.
That way, I can use `net use Z: ...` on windows client working with those auth protocols, so we can map a network drive on the client. (Although it will require to create the cookie beforehand).

Is it doable using SabreDAV as is?
Do you have any docs regarding authentication development?

**Comment by Stoffo** [comment]
Hi @speidy,

generally you can implement any Authentication Method if you write your own Plugin to do so. You just have to implement the BackendInterface provided by sabre/dav

Like that:
```php
<?php

use Sabre\DAV\Auth\Backend\BackendInterface;
use Sabre\HTTP\RequestInterface;
use Sabre\HTTP\ResponseInterface;

class OAuth implements BackendInterface
{
    function check(RequestInterface $request, ResponseInterface $response)
    {
        // Do Stuff to authenticate the user
    }

    function challenge(RequestInterface $request, ResponseInterface $response)
    {
        // Do Stuff when user could not be authenticated
    }
}
```

Hope that is helpful to you!

**Comment by DeepDiver1975** [comment]
@speidy does this answer your question? If not feel free to open this ticket again. THX
