### ISSUE TITLE
php-curl error (calendar export)

### ISSUE THREAD

**Issue by tester19823** [sabre-io/dav#964]
SabreDAV 3.2.2 with loaded ICSExportPlugin generates the output as expected when called with ?export parameter. This works great when requested using command-line curl:
```
curl -u my_user:my_pass --digest http://domain.com/crm/cal.php/calendars/user/calendar_name/?export
```

However, when called in PHP:
```
$url = 'http://domain.com/crm/cal.php/calendars/user/calendar_name/?export';
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_USERPWD, 'my_user:my_pass');
curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_DIGEST);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);  // tried with & without
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);  // tried with & without
$output = curl_exec($ch);
curl_close($ch);
var_dump($output);
```
it generates an error, no matter what settings/options I use:
```
syntax error, unexpected '$yieldFirst' (T_VARIABLE) in <b>/users/xx/public_html/crm/vendor/sabre/dav/lib/DAV/Server.php</b> on line <b>887</b>
```

Is this behaviour expected?
How can I generate .ics dump of a calendar using php-curl?

**Comment by davedags** [comment]
Sounds possibly like a php version error?   It could be that the sabre
version you are running isn't compatible with the php version you are
running.  Just a guess without knowing more.

**Comment by tester19823** [comment]
Yes, I initially thought myself that it had to do with some PHP config. However, but I have replicated this error on two different servers with running several different PHP installations (tried PHP: 5.5, 5.6 and 7.0 - all compatible with SabreDav 3.2).

**Comment by DeepDiver1975** [comment]
3.2.1 introduced a yield call in https://github.com/sabre-io/dav/blob/11ba8e9400d9c3aad8541c6dc19f5f888d9f0804/lib/DAV/Server.php#L887

yield requires php 5.5 minimum - please make sure your server is running at least this version.

closing since this is an issue in the environment
