### ISSUE TITLE
Question: how to remove events in subscription/export mode

### ISSUE THREAD

**Issue by NinoSkopac** [sabre-io/dav#969]
I'm generating a URL like this: https://domain.tld/calendar/UUID.ics
Users subscribe to it with iCalendar and GCalendar. 

When I remove an event server-side, it's not removed on client software. 
I tried setting STATUS property to CANCELLED as per the [RFC](https://tools.ietf.org/html/rfc2445#section-4.8.1.11), but that adds a strikethrough effect, instead of deleting it.

**Is there a way to remove the event completely from client software?**

Code

```php
$vcalendar = new VCalendar();

foreach ($calendarData as $record) {
    $vcalendar->add('VEVENT', [
        'SUMMARY' => $record['summary'],
        'DTSTART' => new \DateTime($record['start_time'], new \DateTimeZone('Australia/Sydney')),
        'DTEND'   => new \DateTime($record['end_time'], new \DateTimeZone('Australia/Sydney')),
    ]);
}

header('Content-Disposition: attachment; filename="' . $_GET['guid'] . '.ics"');
header('Content-Type: text/calendar;charset=UTF-8');

print $vcalendar->serialize();
```

**Comment by DominikTo** [comment]
The problem is likely, that the event is removed, but your client doesn't notice that the URL changed.
Try using the iCS Export Plugin to create iCalendar feeds: http://sabre.io/dav/ics-export-plugin/

**Comment by DeepDiver1975** [comment]
@NinoSkopac question answered? if not please reopen. THX
