### ISSUE TITLE
Office 2016, If header empty when peforming PUT

### ISSUE THREAD

**Issue by datatrippers** [sabre-io/dav#980]
Hi! 
I'm trying to save a file from word 2016 to our webdav server. The lock goes OK, the unlock goes OK, but the PUT action keeps getting a 423 status. 

When I looked into the code I can see you're looking for the if header in the request. The if header is there when it's a LOCK action, but not when it's a PUT action. 

LOCK action:
```
   [if] => Array
                (
                    [0] => If
                    [1] => Array
                        (
                            [0] => (<opaquelocktoken:827de7e2-e52c-43a7-b81d-728e8c8fafe2>)
                        )

                )
```

PUT action, no if header, but there is a:
```
 [lock-token] => Array
                (
                    [0] => Lock-Token
                    [1] => Array
                        (
                            [0] => <opaquelocktoken:827de7e2-e52c-43a7-b81d-728e8c8fafe2>
                        )

                )
```

Maybe they have changed it in word 2016? I'm not 100% sure how to fix this...

**Comment by evert** [comment]
This is definitely non-standard behavior.

**Comment by evert** [comment]
I'd love to see a bug report posted at microsoft, to see if they have something to say about this. Otherwise the only workaround would be to intercept this header and transform it to the correct `If` header so all the other bits in sabre/dav behave as intended.

**Comment by datatrippers** [comment]
Not sure where to post this, can you point us in the right direction? 
For now, I have added a extra check to validateTokens in DAV/Locks/Plugin.php.

https://github.com/fruux/sabre-dav/pull/981

**Comment by staabm** [comment]
I would guess here http://connect.microsoft.com/

**Comment by DeepDiver1975** [comment]
word 2016 :zzz: -> close
