### ISSUE TITLE
iOS not respecting CalendarObject specific ACL

### ISSUE THREAD

**Issue by renekorss** [sabre-io/dav#990]
I have a calendar what is read-write (default calendar ACL), but one event inside that calendar has only read permissions. Now if I try to edit that event in iOS, I'm still allowed.

I have extended `Sabre\CalDAV\Calendar` to achieve event specific ACL (overwrote methods `getChild`, `getChildren` and `getMultipleChildren`).

Each of these overwroted methods are calling below function to set event specific ACL.

```php
/**
 * This method returns the ACL's for calendar objects in this calendar respecting {http://sabredav.org/ns}read-only
 *
 * @param array $obj Event data
 *
 * @return array
 */
public function getRespectfulChildACL($obj)
{
    if (isset($obj['{http://sabredav.org/ns}read-only']) && $obj['{http://sabredav.org/ns}read-only'] === 1) {
        return $this->getReadOnlyACL();
    }

    return $this->getChildACL();
}
```

**For example**

```php
/**
 * Returns a calendar object
 *
 * The contained calendar objects are for example Events or Todo's.
 *
 * @param string $name
 * @return \Sabre\CalDAV\ICalendarObject
 */
public function getChild($name)
{
    $obj = $this->caldavBackend->getCalendarObject($this->calendarInfo['id'], $name);
    if (!$obj) throw new NotFound('Calendar object not found');
    $obj['acl'] = $this->getRespectfulChildACL($obj);

    return new CalendarObject($this->caldavBackend, $this->calendarInfo, $obj);
}

/**
 * This method returns the read-only ACL's for calendar objects in this calendar.
 * The result of this method automatically gets passed to the
 * calendar-object nodes in the calendar.
 *
 * @return array
 */
public function getReadOnlyACL()
{
    return [
        [
            'privilege' => '{DAV:}read',
            'principal' => $this->getOwner(),
            'protected' => true,
        ],
        [
            'privilege' => '{DAV:}read',
            'principal' => $this->getOwner() . '/calendar-proxy-write',
            'protected' => true,
        ],
        [
            'privilege' => '{DAV:}read',
            'principal' => $this->getOwner() . '/calendar-proxy-read',
            'protected' => true,
        ]
    ];
}
```

Event I'm returning from `getCalendarObject`:

```php
$event = [
    'uri' => $originalEvent->getFilename(),
    'lastmodified' => $originalEvent->getUpdatedAt()->getTimestamp(),
    'etag' => '"'.$originalEvent->getETag().'"',
    'calendardata' => $originalEvent->getIcs(),
    'component' => 'vevent',
    '{http://sabredav.org/ns}read-only' => $originalEvent->getReadOnly() ? 1 : 0
];
````
As you can see, I have added internal support for `{http://sabredav.org/ns}read-only` to detect if event is read-only.

Is this known bug from either side? If I mark whole calendar as read-only, then those events will truely be read-only. Problem is only with event specific ACL. 

Any help would be appreciated, cause I have struggled with this for long time now.

**Comment by DeepDiver1975** [comment]
Did you try to use Calendar::getChildACL() - maybe this helps to set the correct acls?

**Comment by renekorss** [comment]
If I view it from browser plugin, then I can see that ACL is read-only. So I suspect that it's only iOS that handles it poorly.
![sabre-event](https://user-images.githubusercontent.com/1494080/31817432-9691b7bc-b59c-11e7-8255-a4f539468a7c.jpg)

**Comment by DeepDiver1975** [comment]
I guess we can close this then. Please reopen if there is anything to be done. THX
