### ISSUE TITLE
duplicate code

### ISSUE THREAD

**Issue by DanielRuf** [sabre-io/dav#995]
collecting parts where we have duplicate code parts but not equal code (bodies)

(quota, remove, ...)
https://github.com/fruux/sabre-dav/blob/master/lib/DAV/FSExt/Directory.php
https://github.com/fruux/sabre-dav/blob/master/lib/DAV/FS/Directory.php

**Comment by DeepDiver1975** [comment]
A pull request to fix this is happily welcome 😉
